# Autogenerated using ProtoBuf.jl v1.2.3


module circuitrules_pb


import ..circuit_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export DropRuleMsg, ReplaceRuleMsg, DecorateRuleMsg, CircuitRule, LossModel


struct DropRuleMsg
    operation::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{DropRuleMsg}) = (;operation = nothing)
PB.field_numbers(::Type{DropRuleMsg}) = (;operation = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DropRuleMsg})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        else
            Base.skip(d, wire_type)
        end
    end
    return DropRuleMsg(operation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DropRuleMsg)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DropRuleMsg)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    return encoded_size
end

struct ReplaceRuleMsg
    operation::Union{Nothing,circuit_pb.Operation}
    replacement::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{ReplaceRuleMsg}) = (;operation = nothing, replacement = nothing)
PB.field_numbers(::Type{ReplaceRuleMsg}) = (;operation = 1, replacement = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ReplaceRuleMsg})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    replacement = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, replacement)
        else
            Base.skip(d, wire_type)
        end
    end
    return ReplaceRuleMsg(operation[], replacement[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ReplaceRuleMsg)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isnothing(x.replacement) && PB.encode(e, 2, x.replacement)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ReplaceRuleMsg)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isnothing(x.replacement) && (encoded_size += PB._encoded_size(x.replacement, 2))
    return encoded_size
end

struct DecorateRuleMsg
    operation::Union{Nothing,circuit_pb.Operation}
    decoration::Union{Nothing,circuit_pb.Operation}
    before::Bool
end
PB.default_values(::Type{DecorateRuleMsg}) = (;operation = nothing, decoration = nothing, before = false)
PB.field_numbers(::Type{DecorateRuleMsg}) = (;operation = 1, decoration = 2, before = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DecorateRuleMsg})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    decoration = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    before = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, decoration)
        elseif field_number == 3
            before = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return DecorateRuleMsg(operation[], decoration[], before)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DecorateRuleMsg)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isnothing(x.decoration) && PB.encode(e, 2, x.decoration)
    x.before != false && PB.encode(e, 3, x.before)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DecorateRuleMsg)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isnothing(x.decoration) && (encoded_size += PB._encoded_size(x.decoration, 2))
    x.before != false && (encoded_size += PB._encoded_size(x.before, 3))
    return encoded_size
end

struct CircuitRule
    kind::Union{Nothing,OneOf{<:Union{DropRuleMsg,DecorateRuleMsg,ReplaceRuleMsg}}}
end
PB.oneof_field_types(::Type{CircuitRule}) = (;
    kind = (;drop_rule=DropRuleMsg, decorate_rule=DecorateRuleMsg, replace_rule=ReplaceRuleMsg),
)
PB.default_values(::Type{CircuitRule}) = (;drop_rule = nothing, decorate_rule = nothing, replace_rule = nothing)
PB.field_numbers(::Type{CircuitRule}) = (;drop_rule = 1, decorate_rule = 2, replace_rule = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CircuitRule})
    kind = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            kind = OneOf(:drop_rule, PB.decode(d, Ref{DropRuleMsg}))
        elseif field_number == 2
            kind = OneOf(:decorate_rule, PB.decode(d, Ref{DecorateRuleMsg}))
        elseif field_number == 3
            kind = OneOf(:replace_rule, PB.decode(d, Ref{ReplaceRuleMsg}))
        else
            Base.skip(d, wire_type)
        end
    end
    return CircuitRule(kind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CircuitRule)
    initpos = position(e.io)
    if isnothing(x.kind);
    elseif x.kind.name === :drop_rule
        PB.encode(e, 1, x.kind[]::DropRuleMsg)
    elseif x.kind.name === :decorate_rule
        PB.encode(e, 2, x.kind[]::DecorateRuleMsg)
    elseif x.kind.name === :replace_rule
        PB.encode(e, 3, x.kind[]::ReplaceRuleMsg)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::CircuitRule)
    encoded_size = 0
    if isnothing(x.kind);
    elseif x.kind.name === :drop_rule
        encoded_size += PB._encoded_size(x.kind[]::DropRuleMsg, 1)
    elseif x.kind.name === :decorate_rule
        encoded_size += PB._encoded_size(x.kind[]::DecorateRuleMsg, 2)
    elseif x.kind.name === :replace_rule
        encoded_size += PB._encoded_size(x.kind[]::ReplaceRuleMsg, 3)
    end
    return encoded_size
end

struct LossModel
    name::String
    rules::Vector{CircuitRule}
end
PB.default_values(::Type{LossModel}) = (;name = "", rules = Vector{CircuitRule}())
PB.field_numbers(::Type{LossModel}) = (;name = 1, rules = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LossModel})
    name = ""
    rules = PB.BufferedVector{CircuitRule}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, rules)
        else
            Base.skip(d, wire_type)
        end
    end
    return LossModel(name, rules[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LossModel)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.rules) && PB.encode(e, 2, x.rules)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LossModel)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.rules) && (encoded_size += PB._encoded_size(x.rules, 2))
    return encoded_size
end
end # module