# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-02-09T16:07:19.749

module circuit_pb


import ..bitvector_pb

import ..pauli_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export GeneralizedAnnotationType, Rational, KrausChannelType, Symbol, GeneralizedType
export OperationType, GateType, GeneralizedOperationType, AnnotationType, Note, Amplitude
export ArgValue, FunctionType, Irrational, OperatorType, GeneralizedAnnotation
export SimpleAnnotation, Arg, ArgFunction, Block, CachedGateCall, ComplexArg, Control
export CustomGate, CustomKrausChannel, CustomOperator, DepolarizingChannel
export ExpectationValue, GateDecl, Generalized, GeneralizedOperation, IfStatement
export Instruction, Inverse, MixedUnitaryChannel, Parallel, PauliChannel, Power, RPauli
export ReadoutErr, Repeat, SimpleGate, SimpleKrausChannel, SimpleOperation, SimpleOperator
export Circuit, Declaration, GateCall, RescaledGate, KrausChannel, Gate, Operator
export Operation
abstract type var"##Abstract#IfStatement" end
abstract type var"##Abstract#GeneralizedOperation" end
abstract type var"##Abstract#ArgFunction" end
abstract type var"##Abstract#RescaledGate" end
abstract type var"##Abstract#CustomKrausChannel" end
abstract type var"##Abstract#CustomGate" end
abstract type var"##Abstract#ExpectationValue" end
abstract type var"##Abstract#Operation" end
abstract type var"##Abstract#SimpleOperator" end
abstract type var"##Abstract#Operator" end
abstract type var"##Abstract#CustomOperator" end
abstract type var"##Abstract#Control" end
abstract type var"##Abstract#RPauli" end
abstract type var"##Abstract#CachedGateCall" end
abstract type var"##Abstract#Parallel" end
abstract type var"##Abstract#Repeat" end
abstract type var"##Abstract#MixedUnitaryChannel" end
abstract type var"##Abstract#Gate" end
abstract type var"##Abstract#Block" end
abstract type var"##Abstract#ReadoutErr" end
abstract type var"##Abstract#KrausChannel" end
abstract type var"##Abstract#PauliChannel" end
abstract type var"##Abstract#SimpleOperation" end
abstract type var"##Abstract#Inverse" end
abstract type var"##Abstract#Declaration" end
abstract type var"##Abstract#DepolarizingChannel" end
abstract type var"##Abstract#SimpleGate" end
abstract type var"##Abstract#ComplexArg" end
abstract type var"##Abstract#Instruction" end
abstract type var"##Abstract#Power" end
abstract type var"##Abstract#Generalized" end
abstract type var"##Abstract#SimpleKrausChannel" end
abstract type var"##Abstract#Circuit" end
abstract type var"##Abstract#GateCall" end
abstract type var"##Abstract#Arg" end
abstract type var"##Abstract#GateDecl" end


@enumx GeneralizedAnnotationType Detector=0 ObservableInclude=1

struct Rational
    num::Int64
    den::Int64
end
PB.default_values(::Type{Rational}) = (;num = zero(Int64), den = zero(Int64))
PB.field_numbers(::Type{Rational}) = (;num = 1, den = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Rational})
    num = zero(Int64)
    den = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            num = PB.decode(d, Int64)
        elseif field_number == 2
            den = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Rational(num, den)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Rational)
    initpos = position(e.io)
    x.num != zero(Int64) && PB.encode(e, 1, x.num)
    x.den != zero(Int64) && PB.encode(e, 2, x.den)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Rational)
    encoded_size = 0
    x.num != zero(Int64) && (encoded_size += PB._encoded_size(x.num, 1))
    x.den != zero(Int64) && (encoded_size += PB._encoded_size(x.den, 2))
    return encoded_size
end

@enumx KrausChannelType ResetX=0 ResetY=1 ResetZ=2 AmplitudeDamping=3 GeneralizedAmplitudeDamping=4 PhaseAmplitudeDamping=5 ThermalNoise=6 PauliX=7 PauliY=8 PauliZ=9 ProjectiveNoiseX=10 ProjectiveNoiseY=11 ProjectiveNoiseZ=12

struct Symbol
    value::String
end
PB.default_values(::Type{Symbol}) = (;value = "")
PB.field_numbers(::Type{Symbol}) = (;value = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Symbol})
    value = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            value = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Symbol(value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Symbol)
    initpos = position(e.io)
    !isempty(x.value) && PB.encode(e, 1, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Symbol)
    encoded_size = 0
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 1))
    return encoded_size
end

@enumx GeneralizedType QFT=0 PhaseGradient=1 PolynomialOracle=2 Diffusion=3 GateRNZ=4

@enumx OperationType MeasureX=0 MeasureY=1 MeasureZ=2 MeasureXX=3 MeasureYY=4 MeasureZZ=5 MeasureResetX=6 MeasureResetY=7 MeasureResetZ=8 BondDim=9 SchmidtRank=10 VonNeumannEntropy=11 Not=12 Pow=13 SetBit0=14 SetBit1=15

@enumx GateType GateID=0 GateX=1 GateY=2 GateZ=3 GateH=4 GateHXY=5 GateHYZ=6 GateS=7 GateT=8 Delay=9 GateU=10 GateP=11 GateRX=12 GateRY=13 GateRZ=14 GateR=15 GateU1=16 GateU2=17 GateU3=18 GateSWAP=19 GateISWAP=20 GateECR=21 GateDCX=22 GateRXX=23 GateRYY=24 GateRZZ=25 GateRZX=26 GateXXplusYY=27 GateXXminusYY=28

@enumx GeneralizedOperationType Barrier=0 Add=1 Multiply=2 And=3 Or=4 Xor=5 ParityCheck=6

@enumx AnnotationType QubitCoordinates=0 ShiftCoordinates=1 Tick=3

struct Note
    note::Union{Nothing,OneOf{<:Union{Int64,Float64}}}
end
PB.oneof_field_types(::Type{Note}) = (;
    note = (;int_note=Int64, double_note=Float64),
)
PB.default_values(::Type{Note}) = (;int_note = zero(Int64), double_note = zero(Float64))
PB.field_numbers(::Type{Note}) = (;int_note = 1, double_note = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Note})
    note = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            note = OneOf(:int_note, PB.decode(d, Int64))
        elseif field_number == 2
            note = OneOf(:double_note, PB.decode(d, Float64))
        else
            Base.skip(d, wire_type)
        end
    end
    return Note(note)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Note)
    initpos = position(e.io)
    if isnothing(x.note);
    elseif x.note.name === :int_note
        PB.encode(e, 1, x.note[]::Int64)
    elseif x.note.name === :double_note
        PB.encode(e, 2, x.note[]::Float64)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Note)
    encoded_size = 0
    if isnothing(x.note);
    elseif x.note.name === :int_note
        encoded_size += PB._encoded_size(x.note[]::Int64, 1)
    elseif x.note.name === :double_note
        encoded_size += PB._encoded_size(x.note[]::Float64, 2)
    end
    return encoded_size
end

struct Amplitude
    bs::Union{Nothing,bitvector_pb.BitVector}
end
PB.default_values(::Type{Amplitude}) = (;bs = nothing)
PB.field_numbers(::Type{Amplitude}) = (;bs = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Amplitude})
    bs = Ref{Union{Nothing,bitvector_pb.BitVector}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, bs)
        else
            Base.skip(d, wire_type)
        end
    end
    return Amplitude(bs[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Amplitude)
    initpos = position(e.io)
    !isnothing(x.bs) && PB.encode(e, 1, x.bs)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Amplitude)
    encoded_size = 0
    !isnothing(x.bs) && (encoded_size += PB._encoded_size(x.bs, 1))
    return encoded_size
end

struct ArgValue
    arg_value::Union{Nothing,OneOf{<:Union{Int64,Float64,Bool}}}
end
PB.oneof_field_types(::Type{ArgValue}) = (;
    arg_value = (;integer_value=Int64, double_value=Float64, bool_value=Bool),
)
PB.default_values(::Type{ArgValue}) = (;integer_value = zero(Int64), double_value = zero(Float64), bool_value = false)
PB.field_numbers(::Type{ArgValue}) = (;integer_value = 1, double_value = 2, bool_value = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ArgValue})
    arg_value = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            arg_value = OneOf(:integer_value, PB.decode(d, Int64))
        elseif field_number == 2
            arg_value = OneOf(:double_value, PB.decode(d, Float64))
        elseif field_number == 3
            arg_value = OneOf(:bool_value, PB.decode(d, Bool))
        else
            Base.skip(d, wire_type)
        end
    end
    return ArgValue(arg_value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ArgValue)
    initpos = position(e.io)
    if isnothing(x.arg_value);
    elseif x.arg_value.name === :integer_value
        PB.encode(e, 1, x.arg_value[]::Int64)
    elseif x.arg_value.name === :double_value
        PB.encode(e, 2, x.arg_value[]::Float64)
    elseif x.arg_value.name === :bool_value
        PB.encode(e, 3, x.arg_value[]::Bool)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::ArgValue)
    encoded_size = 0
    if isnothing(x.arg_value);
    elseif x.arg_value.name === :integer_value
        encoded_size += PB._encoded_size(x.arg_value[]::Int64, 1)
    elseif x.arg_value.name === :double_value
        encoded_size += PB._encoded_size(x.arg_value[]::Float64, 2)
    elseif x.arg_value.name === :bool_value
        encoded_size += PB._encoded_size(x.arg_value[]::Bool, 3)
    end
    return encoded_size
end

@enumx FunctionType ADD=0 MUL=1 DIV=2 POW=3 SIN=5 COS=6 TAN=7 EXP=8 LOG=9 IDENTITY=10

@enumx Irrational PI=0 EULER=1

@enumx OperatorType SigmaMinus=0 SigmaPlus=1 Sigma0001=2 Sigma0010=3 Sigma0011=4 Sigma0110=5 Sigma0111=6 Sigma1011=7 Projector0=8 Projector1=9 Projector00=10 Projector01=11 Projector10=12 Projector11=13 ProjectorX0=14 ProjectorX1=15 ProjectorY0=16 ProjectorY1=17 DiagonalOp=18

struct GeneralizedAnnotation
    mtype::GeneralizedAnnotationType.T
    numqubits::Int64
    numbits::Int64
    numzvars::Int64
    notes::Vector{Note}
end
PB.default_values(::Type{GeneralizedAnnotation}) = (;mtype = GeneralizedAnnotationType.Detector, numqubits = zero(Int64), numbits = zero(Int64), numzvars = zero(Int64), notes = Vector{Note}())
PB.field_numbers(::Type{GeneralizedAnnotation}) = (;mtype = 1, numqubits = 2, numbits = 3, numzvars = 4, notes = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GeneralizedAnnotation})
    mtype = GeneralizedAnnotationType.Detector
    numqubits = zero(Int64)
    numbits = zero(Int64)
    numzvars = zero(Int64)
    notes = PB.BufferedVector{Note}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, GeneralizedAnnotationType.T)
        elseif field_number == 2
            numqubits = PB.decode(d, Int64)
        elseif field_number == 3
            numbits = PB.decode(d, Int64)
        elseif field_number == 4
            numzvars = PB.decode(d, Int64)
        elseif field_number == 5
            PB.decode!(d, notes)
        else
            Base.skip(d, wire_type)
        end
    end
    return GeneralizedAnnotation(mtype, numqubits, numbits, numzvars, notes[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GeneralizedAnnotation)
    initpos = position(e.io)
    x.mtype != GeneralizedAnnotationType.Detector && PB.encode(e, 1, x.mtype)
    x.numqubits != zero(Int64) && PB.encode(e, 2, x.numqubits)
    x.numbits != zero(Int64) && PB.encode(e, 3, x.numbits)
    x.numzvars != zero(Int64) && PB.encode(e, 4, x.numzvars)
    !isempty(x.notes) && PB.encode(e, 5, x.notes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GeneralizedAnnotation)
    encoded_size = 0
    x.mtype != GeneralizedAnnotationType.Detector && (encoded_size += PB._encoded_size(x.mtype, 1))
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 2))
    x.numbits != zero(Int64) && (encoded_size += PB._encoded_size(x.numbits, 3))
    x.numzvars != zero(Int64) && (encoded_size += PB._encoded_size(x.numzvars, 4))
    !isempty(x.notes) && (encoded_size += PB._encoded_size(x.notes, 5))
    return encoded_size
end

struct SimpleAnnotation
    mtype::AnnotationType.T
    notes::Vector{Note}
end
PB.default_values(::Type{SimpleAnnotation}) = (;mtype = AnnotationType.QubitCoordinates, notes = Vector{Note}())
PB.field_numbers(::Type{SimpleAnnotation}) = (;mtype = 1, notes = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimpleAnnotation})
    mtype = AnnotationType.QubitCoordinates
    notes = PB.BufferedVector{Note}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, AnnotationType.T)
        elseif field_number == 2
            PB.decode!(d, notes)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimpleAnnotation(mtype, notes[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimpleAnnotation)
    initpos = position(e.io)
    x.mtype != AnnotationType.QubitCoordinates && PB.encode(e, 1, x.mtype)
    !isempty(x.notes) && PB.encode(e, 2, x.notes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimpleAnnotation)
    encoded_size = 0
    x.mtype != AnnotationType.QubitCoordinates && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.notes) && (encoded_size += PB._encoded_size(x.notes, 2))
    return encoded_size
end

# Stub definitions for cyclic types
struct var"##Stub#Arg"{T1<:var"##Abstract#ArgFunction"} <: var"##Abstract#Arg"
    arg::Union{Nothing,OneOf{<:Union{ArgValue,Symbol,T1,Irrational.T}}}
end

struct var"##Stub#ArgFunction" <: var"##Abstract#ArgFunction"
    mtype::FunctionType.T
    args::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#Block"{T1<:var"##Abstract#Instruction"} <: var"##Abstract#Block"
    numqubits::Int64
    numbits::Int64
    numzvars::Int64
    instructions::Vector{T1}
end

struct var"##Stub#CachedGateCall" <: var"##Abstract#CachedGateCall"
    id::UInt64
    args::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#ComplexArg" <: var"##Abstract#ComplexArg"
    real::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
    imag::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#Control"{T1<:var"##Abstract#Gate"} <: var"##Abstract#Control"
    operation::Union{Nothing,T1}
    numcontrols::Int64
end

struct var"##Stub#CustomGate" <: var"##Abstract#CustomGate"
    numqubits::Int64
    matrix::Vector{var"##Stub#ComplexArg"}
end

struct var"##Stub#CustomKrausChannel"{T1<:var"##Abstract#Operator"} <: var"##Abstract#CustomKrausChannel"
    numqubits::Int64
    operators::Vector{T1}
end

struct var"##Stub#CustomOperator" <: var"##Abstract#CustomOperator"
    numqubits::Int64
    matrix::Vector{var"##Stub#ComplexArg"}
end

struct var"##Stub#DepolarizingChannel" <: var"##Abstract#DepolarizingChannel"
    numqubits::Int64
    probability::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#ExpectationValue"{T1<:var"##Abstract#Operator"} <: var"##Abstract#ExpectationValue"
    operator::Union{Nothing,T1}
end

struct var"##Stub#GateDecl"{T1<:var"##Abstract#Instruction"} <: var"##Abstract#GateDecl"
    name::String
    args::Vector{Symbol}
    instructions::Vector{T1}
end

struct var"##Stub#Generalized" <: var"##Abstract#Generalized"
    mtype::GeneralizedType.T
    args::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
    qregsizes::Vector{Int64}
end

struct var"##Stub#GeneralizedOperation" <: var"##Abstract#GeneralizedOperation"
    mtype::GeneralizedOperationType.T
    numqubits::Int64
    numbits::Int64
    numzvars::Int64
    parameters::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#IfStatement"{T1<:var"##Abstract#Operation"} <: var"##Abstract#IfStatement"
    operation::Union{Nothing,T1}
    bitstring::Union{Nothing,bitvector_pb.BitVector}
end

struct var"##Stub#Instruction"{T1<:var"##Abstract#Operation"} <: var"##Abstract#Instruction"
    operation::Union{Nothing,T1}
    qtargets::Vector{Int64}
    ctargets::Vector{Int64}
    ztargets::Vector{Int64}
end

struct var"##Stub#Inverse"{T1<:var"##Abstract#Gate"} <: var"##Abstract#Inverse"
    operation::Union{Nothing,T1}
end

struct var"##Stub#MixedUnitaryChannel"{T1<:var"##Abstract#RescaledGate"} <: var"##Abstract#MixedUnitaryChannel"
    operators::Vector{T1}
end

struct var"##Stub#Parallel"{T1<:var"##Abstract#Gate"} <: var"##Abstract#Parallel"
    operation::Union{Nothing,T1}
    numrepeats::Int64
end

struct var"##Stub#PauliChannel" <: var"##Abstract#PauliChannel"
    probabilities::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
    paulistrings::Vector{pauli_pb.PauliString}
end

struct var"##Stub#Power"{T1<:var"##Abstract#Gate"} <: var"##Abstract#Power"
    operation::Union{Nothing,T1}
    power::Union{Nothing,OneOf{<:Union{Float64,Rational,Int64}}}
end

struct var"##Stub#RPauli" <: var"##Abstract#RPauli"
    pauli::Union{Nothing,pauli_pb.PauliString}
    theta::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#ReadoutErr" <: var"##Abstract#ReadoutErr"
    p0::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
    p1::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#Repeat"{T1<:var"##Abstract#Operation"} <: var"##Abstract#Repeat"
    numrepeats::Int64
    operation::Union{Nothing,T1}
end

struct var"##Stub#SimpleGate" <: var"##Abstract#SimpleGate"
    mtype::GateType.T
    parameters::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#SimpleKrausChannel" <: var"##Abstract#SimpleKrausChannel"
    mtype::KrausChannelType.T
    parameters::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#SimpleOperation" <: var"##Abstract#SimpleOperation"
    mtype::OperationType.T
    parameters::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#SimpleOperator" <: var"##Abstract#SimpleOperator"
    mtype::OperatorType.T
    parameters::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#Circuit"{T1<:var"##Abstract#Operation",T2<:var"##Abstract#Declaration"} <: var"##Abstract#Circuit"
    instructions::Vector{var"##Stub#Instruction"{T1}}
    decls::Dict{UInt64,T2}
    declorder::Vector{UInt64}
end

struct var"##Stub#Declaration"{T1<:var"##Abstract#Operation"} <: var"##Abstract#Declaration"
    decl::Union{Nothing,OneOf{<:Union{var"##Stub#GateDecl"{var"##Stub#Instruction"{T1}},var"##Stub#Block"{var"##Stub#Instruction"{T1}}}}}
end

struct var"##Stub#GateCall"{T1<:var"##Abstract#Operation"} <: var"##Abstract#GateCall"
    decl::Union{Nothing,var"##Stub#GateDecl"{var"##Stub#Instruction"{T1}}}
    args::Vector{var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#RescaledGate"{T1<:var"##Abstract#Gate"} <: var"##Abstract#RescaledGate"
    operation::Union{Nothing,T1}
    scale::Union{Nothing,var"##Stub#Arg"{var"##Stub#ArgFunction"}}
end

struct var"##Stub#KrausChannel"{T1<:var"##Abstract#Operator",T2<:var"##Abstract#Gate"} <: var"##Abstract#KrausChannel"
    krauschannel::Union{Nothing,OneOf{<:Union{var"##Stub#SimpleKrausChannel",var"##Stub#CustomKrausChannel"{T1},var"##Stub#DepolarizingChannel",var"##Stub#MixedUnitaryChannel"{var"##Stub#RescaledGate"{T2}},var"##Stub#PauliChannel"}}}
end

struct var"##Stub#Gate"{T1<:var"##Abstract#Operation"} <: var"##Abstract#Gate"
    gate::Union{Nothing,OneOf{<:Union{var"##Stub#SimpleGate",var"##Stub#CustomGate",var"##Stub#Generalized",var"##Stub#Control"{var"##Stub#Gate"{T1}},var"##Stub#Power"{var"##Stub#Gate"{T1}},var"##Stub#Inverse"{var"##Stub#Gate"{T1}},var"##Stub#Parallel"{var"##Stub#Gate"{T1}},var"##Stub#GateCall"{T1},pauli_pb.PauliString,var"##Stub#CachedGateCall",var"##Stub#RPauli"}}}
end

struct var"##Stub#Operator"{T1<:var"##Abstract#Operation"} <: var"##Abstract#Operator"
    operator::Union{Nothing,OneOf{<:Union{var"##Stub#SimpleGate",var"##Stub#CustomGate",var"##Stub#Generalized",var"##Stub#Control"{var"##Stub#Gate"{T1}},var"##Stub#Power"{var"##Stub#Gate"{T1}},var"##Stub#Inverse"{var"##Stub#Gate"{T1}},var"##Stub#Parallel"{var"##Stub#Gate"{T1}},var"##Stub#GateCall"{T1},pauli_pb.PauliString,var"##Stub#SimpleOperator",var"##Stub#CustomOperator",var"##Stub#RescaledGate"{var"##Stub#Gate"{T1}},var"##Stub#CachedGateCall",var"##Stub#RPauli"}}}
end

struct var"##Stub#Operation" <: var"##Abstract#Operation"
    operation::Union{Nothing,OneOf{<:Union{var"##Stub#SimpleGate",var"##Stub#CustomGate",var"##Stub#Generalized",var"##Stub#Control"{var"##Stub#Gate"{var"##Stub#Operation"}},var"##Stub#Power"{var"##Stub#Gate"{var"##Stub#Operation"}},var"##Stub#Inverse"{var"##Stub#Gate"{var"##Stub#Operation"}},var"##Stub#Parallel"{var"##Stub#Gate"{var"##Stub#Operation"}},var"##Stub#GateCall"{var"##Stub#Operation"},pauli_pb.PauliString,var"##Stub#SimpleKrausChannel",var"##Stub#CustomKrausChannel"{var"##Stub#Operator"{var"##Stub#Operation"}},var"##Stub#DepolarizingChannel",var"##Stub#MixedUnitaryChannel"{var"##Stub#RescaledGate"{var"##Stub#Gate"{var"##Stub#Operation"}}},var"##Stub#PauliChannel",var"##Stub#SimpleOperator",var"##Stub#CustomOperator",var"##Stub#RescaledGate"{var"##Stub#Gate"{var"##Stub#Operation"}},var"##Stub#SimpleOperation",var"##Stub#IfStatement"{var"##Stub#Operation"},var"##Stub#GeneralizedOperation",Amplitude,var"##Stub#ExpectationValue"{var"##Stub#Operator"{var"##Stub#Operation"}},SimpleAnnotation,GeneralizedAnnotation,var"##Stub#CachedGateCall",var"##Stub#RPauli",var"##Stub#Repeat"{var"##Stub#Operation"},var"##Stub#Block"{var"##Stub#Instruction"{var"##Stub#Operation"}},var"##Stub#ReadoutErr"}}}
end

const Arg = var"##Stub#Arg"{var"##Stub#ArgFunction"}
PB.oneof_field_types(::Type{Arg}) = (;
    arg = (;argvalue_value=ArgValue, symbol_value=Symbol, argfunction_value=ArgFunction, irrational_value=Irrational.T),
)
PB.default_values(::Type{Arg}) = (;argvalue_value = nothing, symbol_value = nothing, argfunction_value = nothing, irrational_value = Irrational.PI)
PB.field_numbers(::Type{Arg}) = (;argvalue_value = 1, symbol_value = 2, argfunction_value = 3, irrational_value = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Arg})
    arg = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            arg = OneOf(:argvalue_value, PB.decode(d, Ref{ArgValue}))
        elseif field_number == 2
            arg = OneOf(:symbol_value, PB.decode(d, Ref{Symbol}))
        elseif field_number == 3
            arg = OneOf(:argfunction_value, PB.decode(d, Ref{ArgFunction}))
        elseif field_number == 4
            arg = OneOf(:irrational_value, PB.decode(d, Irrational.T))
        else
            Base.skip(d, wire_type)
        end
    end
    return Arg(arg)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Arg)
    initpos = position(e.io)
    if isnothing(x.arg);
    elseif x.arg.name === :argvalue_value
        PB.encode(e, 1, x.arg[]::ArgValue)
    elseif x.arg.name === :symbol_value
        PB.encode(e, 2, x.arg[]::Symbol)
    elseif x.arg.name === :argfunction_value
        PB.encode(e, 3, x.arg[]::ArgFunction)
    elseif x.arg.name === :irrational_value
        PB.encode(e, 4, x.arg[]::Irrational.T)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Arg)
    encoded_size = 0
    if isnothing(x.arg);
    elseif x.arg.name === :argvalue_value
        encoded_size += PB._encoded_size(x.arg[]::ArgValue, 1)
    elseif x.arg.name === :symbol_value
        encoded_size += PB._encoded_size(x.arg[]::Symbol, 2)
    elseif x.arg.name === :argfunction_value
        encoded_size += PB._encoded_size(x.arg[]::ArgFunction, 3)
    elseif x.arg.name === :irrational_value
        encoded_size += PB._encoded_size(x.arg[]::Irrational.T, 4)
    end
    return encoded_size
end

const ArgFunction = var"##Stub#ArgFunction"
PB.default_values(::Type{ArgFunction}) = (;mtype = FunctionType.ADD, args = Vector{Arg}())
PB.field_numbers(::Type{ArgFunction}) = (;mtype = 1, args = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ArgFunction})
    mtype = FunctionType.ADD
    args = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, FunctionType.T)
        elseif field_number == 2
            PB.decode!(d, args)
        else
            Base.skip(d, wire_type)
        end
    end
    return ArgFunction(mtype, args[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ArgFunction)
    initpos = position(e.io)
    x.mtype != FunctionType.ADD && PB.encode(e, 1, x.mtype)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ArgFunction)
    encoded_size = 0
    x.mtype != FunctionType.ADD && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    return encoded_size
end

const Block = var"##Stub#Block"{var"##Stub#Instruction"{var"##Stub#Operation"}}
PB.default_values(::Type{Block}) = (;numqubits = zero(Int64), numbits = zero(Int64), numzvars = zero(Int64), instructions = Vector{Instruction}())
PB.field_numbers(::Type{Block}) = (;numqubits = 1, numbits = 2, numzvars = 3, instructions = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Block})
    numqubits = zero(Int64)
    numbits = zero(Int64)
    numzvars = zero(Int64)
    instructions = PB.BufferedVector{Instruction}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            numbits = PB.decode(d, Int64)
        elseif field_number == 3
            numzvars = PB.decode(d, Int64)
        elseif field_number == 4
            PB.decode!(d, instructions)
        else
            Base.skip(d, wire_type)
        end
    end
    return Block(numqubits, numbits, numzvars, instructions[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Block)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    x.numbits != zero(Int64) && PB.encode(e, 2, x.numbits)
    x.numzvars != zero(Int64) && PB.encode(e, 3, x.numzvars)
    !isempty(x.instructions) && PB.encode(e, 4, x.instructions)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Block)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    x.numbits != zero(Int64) && (encoded_size += PB._encoded_size(x.numbits, 2))
    x.numzvars != zero(Int64) && (encoded_size += PB._encoded_size(x.numzvars, 3))
    !isempty(x.instructions) && (encoded_size += PB._encoded_size(x.instructions, 4))
    return encoded_size
end

const CachedGateCall = var"##Stub#CachedGateCall"
PB.default_values(::Type{CachedGateCall}) = (;id = zero(UInt64), args = Vector{Arg}())
PB.field_numbers(::Type{CachedGateCall}) = (;id = 1, args = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CachedGateCall})
    id = zero(UInt64)
    args = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, UInt64)
        elseif field_number == 2
            PB.decode!(d, args)
        else
            Base.skip(d, wire_type)
        end
    end
    return CachedGateCall(id, args[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CachedGateCall)
    initpos = position(e.io)
    x.id != zero(UInt64) && PB.encode(e, 1, x.id)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CachedGateCall)
    encoded_size = 0
    x.id != zero(UInt64) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    return encoded_size
end

const ComplexArg = var"##Stub#ComplexArg"
PB.default_values(::Type{ComplexArg}) = (;real = nothing, imag = nothing)
PB.field_numbers(::Type{ComplexArg}) = (;real = 1, imag = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ComplexArg})
    real = Ref{Union{Nothing,Arg}}(nothing)
    imag = Ref{Union{Nothing,Arg}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, real)
        elseif field_number == 2
            PB.decode!(d, imag)
        else
            Base.skip(d, wire_type)
        end
    end
    return ComplexArg(real[], imag[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ComplexArg)
    initpos = position(e.io)
    !isnothing(x.real) && PB.encode(e, 1, x.real)
    !isnothing(x.imag) && PB.encode(e, 2, x.imag)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ComplexArg)
    encoded_size = 0
    !isnothing(x.real) && (encoded_size += PB._encoded_size(x.real, 1))
    !isnothing(x.imag) && (encoded_size += PB._encoded_size(x.imag, 2))
    return encoded_size
end

const Control = var"##Stub#Control"{var"##Stub#Gate"{var"##Stub#Operation"}}
PB.default_values(::Type{Control}) = (;operation = nothing, numcontrols = zero(Int64))
PB.field_numbers(::Type{Control}) = (;operation = 1, numcontrols = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Control})
    operation = Ref{Union{Nothing,Gate}}(nothing)
    numcontrols = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            numcontrols = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Control(operation[], numcontrols)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Control)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    x.numcontrols != zero(Int64) && PB.encode(e, 2, x.numcontrols)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Control)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    x.numcontrols != zero(Int64) && (encoded_size += PB._encoded_size(x.numcontrols, 2))
    return encoded_size
end

const CustomGate = var"##Stub#CustomGate"
PB.default_values(::Type{CustomGate}) = (;numqubits = zero(Int64), matrix = Vector{ComplexArg}())
PB.field_numbers(::Type{CustomGate}) = (;numqubits = 1, matrix = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CustomGate})
    numqubits = zero(Int64)
    matrix = PB.BufferedVector{ComplexArg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, matrix)
        else
            Base.skip(d, wire_type)
        end
    end
    return CustomGate(numqubits, matrix[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CustomGate)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    !isempty(x.matrix) && PB.encode(e, 2, x.matrix)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CustomGate)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    !isempty(x.matrix) && (encoded_size += PB._encoded_size(x.matrix, 2))
    return encoded_size
end

const CustomKrausChannel = var"##Stub#CustomKrausChannel"{var"##Stub#Operator"{var"##Stub#Operation"}}
PB.default_values(::Type{CustomKrausChannel}) = (;numqubits = zero(Int64), operators = Vector{Operator}())
PB.field_numbers(::Type{CustomKrausChannel}) = (;numqubits = 1, operators = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CustomKrausChannel})
    numqubits = zero(Int64)
    operators = PB.BufferedVector{Operator}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, operators)
        else
            Base.skip(d, wire_type)
        end
    end
    return CustomKrausChannel(numqubits, operators[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CustomKrausChannel)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    !isempty(x.operators) && PB.encode(e, 2, x.operators)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CustomKrausChannel)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    !isempty(x.operators) && (encoded_size += PB._encoded_size(x.operators, 2))
    return encoded_size
end

const CustomOperator = var"##Stub#CustomOperator"
PB.default_values(::Type{CustomOperator}) = (;numqubits = zero(Int64), matrix = Vector{ComplexArg}())
PB.field_numbers(::Type{CustomOperator}) = (;numqubits = 1, matrix = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CustomOperator})
    numqubits = zero(Int64)
    matrix = PB.BufferedVector{ComplexArg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, matrix)
        else
            Base.skip(d, wire_type)
        end
    end
    return CustomOperator(numqubits, matrix[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CustomOperator)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    !isempty(x.matrix) && PB.encode(e, 2, x.matrix)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CustomOperator)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    !isempty(x.matrix) && (encoded_size += PB._encoded_size(x.matrix, 2))
    return encoded_size
end

const DepolarizingChannel = var"##Stub#DepolarizingChannel"
PB.default_values(::Type{DepolarizingChannel}) = (;numqubits = zero(Int64), probability = nothing)
PB.field_numbers(::Type{DepolarizingChannel}) = (;numqubits = 1, probability = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DepolarizingChannel})
    numqubits = zero(Int64)
    probability = Ref{Union{Nothing,Arg}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, probability)
        else
            Base.skip(d, wire_type)
        end
    end
    return DepolarizingChannel(numqubits, probability[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DepolarizingChannel)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    !isnothing(x.probability) && PB.encode(e, 2, x.probability)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DepolarizingChannel)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    !isnothing(x.probability) && (encoded_size += PB._encoded_size(x.probability, 2))
    return encoded_size
end

const ExpectationValue = var"##Stub#ExpectationValue"{var"##Stub#Operator"{var"##Stub#Operation"}}
PB.default_values(::Type{ExpectationValue}) = (;operator = nothing)
PB.field_numbers(::Type{ExpectationValue}) = (;operator = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExpectationValue})
    operator = Ref{Union{Nothing,Operator}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operator)
        else
            Base.skip(d, wire_type)
        end
    end
    return ExpectationValue(operator[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExpectationValue)
    initpos = position(e.io)
    !isnothing(x.operator) && PB.encode(e, 1, x.operator)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExpectationValue)
    encoded_size = 0
    !isnothing(x.operator) && (encoded_size += PB._encoded_size(x.operator, 1))
    return encoded_size
end

const GateDecl = var"##Stub#GateDecl"{var"##Stub#Instruction"{var"##Stub#Operation"}}
PB.default_values(::Type{GateDecl}) = (;name = "", args = Vector{Symbol}(), instructions = Vector{Instruction}())
PB.field_numbers(::Type{GateDecl}) = (;name = 1, args = 2, instructions = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GateDecl})
    name = ""
    args = PB.BufferedVector{Symbol}()
    instructions = PB.BufferedVector{Instruction}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        elseif field_number == 3
            PB.decode!(d, instructions)
        else
            Base.skip(d, wire_type)
        end
    end
    return GateDecl(name, args[], instructions[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GateDecl)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    !isempty(x.instructions) && PB.encode(e, 3, x.instructions)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GateDecl)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    !isempty(x.instructions) && (encoded_size += PB._encoded_size(x.instructions, 3))
    return encoded_size
end

const Generalized = var"##Stub#Generalized"
PB.default_values(::Type{Generalized}) = (;mtype = GeneralizedType.QFT, args = Vector{Arg}(), qregsizes = Vector{Int64}())
PB.field_numbers(::Type{Generalized}) = (;mtype = 1, args = 2, qregsizes = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Generalized})
    mtype = GeneralizedType.QFT
    args = PB.BufferedVector{Arg}()
    qregsizes = PB.BufferedVector{Int64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, GeneralizedType.T)
        elseif field_number == 2
            PB.decode!(d, args)
        elseif field_number == 3
            PB.decode!(d, wire_type, qregsizes)
        else
            Base.skip(d, wire_type)
        end
    end
    return Generalized(mtype, args[], qregsizes[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Generalized)
    initpos = position(e.io)
    x.mtype != GeneralizedType.QFT && PB.encode(e, 1, x.mtype)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    !isempty(x.qregsizes) && PB.encode(e, 3, x.qregsizes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Generalized)
    encoded_size = 0
    x.mtype != GeneralizedType.QFT && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    !isempty(x.qregsizes) && (encoded_size += PB._encoded_size(x.qregsizes, 3))
    return encoded_size
end

const GeneralizedOperation = var"##Stub#GeneralizedOperation"
PB.default_values(::Type{GeneralizedOperation}) = (;mtype = GeneralizedOperationType.Barrier, numqubits = zero(Int64), numbits = zero(Int64), numzvars = zero(Int64), parameters = Vector{Arg}())
PB.field_numbers(::Type{GeneralizedOperation}) = (;mtype = 1, numqubits = 2, numbits = 3, numzvars = 4, parameters = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GeneralizedOperation})
    mtype = GeneralizedOperationType.Barrier
    numqubits = zero(Int64)
    numbits = zero(Int64)
    numzvars = zero(Int64)
    parameters = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, GeneralizedOperationType.T)
        elseif field_number == 2
            numqubits = PB.decode(d, Int64)
        elseif field_number == 3
            numbits = PB.decode(d, Int64)
        elseif field_number == 4
            numzvars = PB.decode(d, Int64)
        elseif field_number == 5
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return GeneralizedOperation(mtype, numqubits, numbits, numzvars, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GeneralizedOperation)
    initpos = position(e.io)
    x.mtype != GeneralizedOperationType.Barrier && PB.encode(e, 1, x.mtype)
    x.numqubits != zero(Int64) && PB.encode(e, 2, x.numqubits)
    x.numbits != zero(Int64) && PB.encode(e, 3, x.numbits)
    x.numzvars != zero(Int64) && PB.encode(e, 4, x.numzvars)
    !isempty(x.parameters) && PB.encode(e, 5, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GeneralizedOperation)
    encoded_size = 0
    x.mtype != GeneralizedOperationType.Barrier && (encoded_size += PB._encoded_size(x.mtype, 1))
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 2))
    x.numbits != zero(Int64) && (encoded_size += PB._encoded_size(x.numbits, 3))
    x.numzvars != zero(Int64) && (encoded_size += PB._encoded_size(x.numzvars, 4))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 5))
    return encoded_size
end

const IfStatement = var"##Stub#IfStatement"{var"##Stub#Operation"}
PB.default_values(::Type{IfStatement}) = (;operation = nothing, bitstring = nothing)
PB.field_numbers(::Type{IfStatement}) = (;operation = 1, bitstring = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IfStatement})
    operation = Ref{Union{Nothing,Operation}}(nothing)
    bitstring = Ref{Union{Nothing,bitvector_pb.BitVector}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, bitstring)
        else
            Base.skip(d, wire_type)
        end
    end
    return IfStatement(operation[], bitstring[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IfStatement)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isnothing(x.bitstring) && PB.encode(e, 2, x.bitstring)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IfStatement)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isnothing(x.bitstring) && (encoded_size += PB._encoded_size(x.bitstring, 2))
    return encoded_size
end

const Instruction = var"##Stub#Instruction"{var"##Stub#Operation"}
PB.default_values(::Type{Instruction}) = (;operation = nothing, qtargets = Vector{Int64}(), ctargets = Vector{Int64}(), ztargets = Vector{Int64}())
PB.field_numbers(::Type{Instruction}) = (;operation = 1, qtargets = 2, ctargets = 3, ztargets = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Instruction})
    operation = Ref{Union{Nothing,Operation}}(nothing)
    qtargets = PB.BufferedVector{Int64}()
    ctargets = PB.BufferedVector{Int64}()
    ztargets = PB.BufferedVector{Int64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, wire_type, qtargets)
        elseif field_number == 3
            PB.decode!(d, wire_type, ctargets)
        elseif field_number == 4
            PB.decode!(d, wire_type, ztargets)
        else
            Base.skip(d, wire_type)
        end
    end
    return Instruction(operation[], qtargets[], ctargets[], ztargets[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Instruction)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isempty(x.qtargets) && PB.encode(e, 2, x.qtargets)
    !isempty(x.ctargets) && PB.encode(e, 3, x.ctargets)
    !isempty(x.ztargets) && PB.encode(e, 4, x.ztargets)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Instruction)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isempty(x.qtargets) && (encoded_size += PB._encoded_size(x.qtargets, 2))
    !isempty(x.ctargets) && (encoded_size += PB._encoded_size(x.ctargets, 3))
    !isempty(x.ztargets) && (encoded_size += PB._encoded_size(x.ztargets, 4))
    return encoded_size
end

const Inverse = var"##Stub#Inverse"{var"##Stub#Gate"{var"##Stub#Operation"}}
PB.default_values(::Type{Inverse}) = (;operation = nothing)
PB.field_numbers(::Type{Inverse}) = (;operation = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Inverse})
    operation = Ref{Union{Nothing,Gate}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        else
            Base.skip(d, wire_type)
        end
    end
    return Inverse(operation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Inverse)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Inverse)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    return encoded_size
end

const MixedUnitaryChannel = var"##Stub#MixedUnitaryChannel"{var"##Stub#RescaledGate"{var"##Stub#Gate"{var"##Stub#Operation"}}}
PB.default_values(::Type{MixedUnitaryChannel}) = (;operators = Vector{RescaledGate}())
PB.field_numbers(::Type{MixedUnitaryChannel}) = (;operators = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MixedUnitaryChannel})
    operators = PB.BufferedVector{RescaledGate}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operators)
        else
            Base.skip(d, wire_type)
        end
    end
    return MixedUnitaryChannel(operators[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MixedUnitaryChannel)
    initpos = position(e.io)
    !isempty(x.operators) && PB.encode(e, 1, x.operators)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MixedUnitaryChannel)
    encoded_size = 0
    !isempty(x.operators) && (encoded_size += PB._encoded_size(x.operators, 1))
    return encoded_size
end

const Parallel = var"##Stub#Parallel"{var"##Stub#Gate"{var"##Stub#Operation"}}
PB.default_values(::Type{Parallel}) = (;operation = nothing, numrepeats = zero(Int64))
PB.field_numbers(::Type{Parallel}) = (;operation = 1, numrepeats = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Parallel})
    operation = Ref{Union{Nothing,Gate}}(nothing)
    numrepeats = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            numrepeats = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Parallel(operation[], numrepeats)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Parallel)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    x.numrepeats != zero(Int64) && PB.encode(e, 2, x.numrepeats)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Parallel)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    x.numrepeats != zero(Int64) && (encoded_size += PB._encoded_size(x.numrepeats, 2))
    return encoded_size
end

const PauliChannel = var"##Stub#PauliChannel"
PB.default_values(::Type{PauliChannel}) = (;probabilities = Vector{Arg}(), paulistrings = Vector{pauli_pb.PauliString}())
PB.field_numbers(::Type{PauliChannel}) = (;probabilities = 1, paulistrings = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:PauliChannel})
    probabilities = PB.BufferedVector{Arg}()
    paulistrings = PB.BufferedVector{pauli_pb.PauliString}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, probabilities)
        elseif field_number == 2
            PB.decode!(d, paulistrings)
        else
            Base.skip(d, wire_type)
        end
    end
    return PauliChannel(probabilities[], paulistrings[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::PauliChannel)
    initpos = position(e.io)
    !isempty(x.probabilities) && PB.encode(e, 1, x.probabilities)
    !isempty(x.paulistrings) && PB.encode(e, 2, x.paulistrings)
    return position(e.io) - initpos
end
function PB._encoded_size(x::PauliChannel)
    encoded_size = 0
    !isempty(x.probabilities) && (encoded_size += PB._encoded_size(x.probabilities, 1))
    !isempty(x.paulistrings) && (encoded_size += PB._encoded_size(x.paulistrings, 2))
    return encoded_size
end

const Power = var"##Stub#Power"{var"##Stub#Gate"{var"##Stub#Operation"}}
PB.oneof_field_types(::Type{Power}) = (;
    power = (;double_val=Float64, rational_val=Rational, int_val=Int64),
)
PB.default_values(::Type{Power}) = (;operation = nothing, double_val = zero(Float64), rational_val = nothing, int_val = zero(Int64))
PB.field_numbers(::Type{Power}) = (;operation = 1, double_val = 2, rational_val = 3, int_val = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Power})
    operation = Ref{Union{Nothing,Gate}}(nothing)
    power = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            power = OneOf(:double_val, PB.decode(d, Float64))
        elseif field_number == 3
            power = OneOf(:rational_val, PB.decode(d, Ref{Rational}))
        elseif field_number == 4
            power = OneOf(:int_val, PB.decode(d, Int64))
        else
            Base.skip(d, wire_type)
        end
    end
    return Power(operation[], power)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Power)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    if isnothing(x.power);
    elseif x.power.name === :double_val
        PB.encode(e, 2, x.power[]::Float64)
    elseif x.power.name === :rational_val
        PB.encode(e, 3, x.power[]::Rational)
    elseif x.power.name === :int_val
        PB.encode(e, 4, x.power[]::Int64)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Power)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    if isnothing(x.power);
    elseif x.power.name === :double_val
        encoded_size += PB._encoded_size(x.power[]::Float64, 2)
    elseif x.power.name === :rational_val
        encoded_size += PB._encoded_size(x.power[]::Rational, 3)
    elseif x.power.name === :int_val
        encoded_size += PB._encoded_size(x.power[]::Int64, 4)
    end
    return encoded_size
end

const RPauli = var"##Stub#RPauli"
PB.default_values(::Type{RPauli}) = (;pauli = nothing, theta = nothing)
PB.field_numbers(::Type{RPauli}) = (;pauli = 1, theta = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RPauli})
    pauli = Ref{Union{Nothing,pauli_pb.PauliString}}(nothing)
    theta = Ref{Union{Nothing,Arg}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, pauli)
        elseif field_number == 2
            PB.decode!(d, theta)
        else
            Base.skip(d, wire_type)
        end
    end
    return RPauli(pauli[], theta[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RPauli)
    initpos = position(e.io)
    !isnothing(x.pauli) && PB.encode(e, 1, x.pauli)
    !isnothing(x.theta) && PB.encode(e, 2, x.theta)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RPauli)
    encoded_size = 0
    !isnothing(x.pauli) && (encoded_size += PB._encoded_size(x.pauli, 1))
    !isnothing(x.theta) && (encoded_size += PB._encoded_size(x.theta, 2))
    return encoded_size
end

const ReadoutErr = var"##Stub#ReadoutErr"
PB.default_values(::Type{ReadoutErr}) = (;p0 = nothing, p1 = nothing)
PB.field_numbers(::Type{ReadoutErr}) = (;p0 = 1, p1 = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ReadoutErr})
    p0 = Ref{Union{Nothing,Arg}}(nothing)
    p1 = Ref{Union{Nothing,Arg}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, p0)
        elseif field_number == 2
            PB.decode!(d, p1)
        else
            Base.skip(d, wire_type)
        end
    end
    return ReadoutErr(p0[], p1[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ReadoutErr)
    initpos = position(e.io)
    !isnothing(x.p0) && PB.encode(e, 1, x.p0)
    !isnothing(x.p1) && PB.encode(e, 2, x.p1)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ReadoutErr)
    encoded_size = 0
    !isnothing(x.p0) && (encoded_size += PB._encoded_size(x.p0, 1))
    !isnothing(x.p1) && (encoded_size += PB._encoded_size(x.p1, 2))
    return encoded_size
end

const Repeat = var"##Stub#Repeat"{var"##Stub#Operation"}
PB.default_values(::Type{Repeat}) = (;numrepeats = zero(Int64), operation = nothing)
PB.field_numbers(::Type{Repeat}) = (;numrepeats = 1, operation = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Repeat})
    numrepeats = zero(Int64)
    operation = Ref{Union{Nothing,Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numrepeats = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, operation)
        else
            Base.skip(d, wire_type)
        end
    end
    return Repeat(numrepeats, operation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Repeat)
    initpos = position(e.io)
    x.numrepeats != zero(Int64) && PB.encode(e, 1, x.numrepeats)
    !isnothing(x.operation) && PB.encode(e, 2, x.operation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Repeat)
    encoded_size = 0
    x.numrepeats != zero(Int64) && (encoded_size += PB._encoded_size(x.numrepeats, 1))
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 2))
    return encoded_size
end

const SimpleGate = var"##Stub#SimpleGate"
PB.default_values(::Type{SimpleGate}) = (;mtype = GateType.GateID, parameters = Vector{Arg}())
PB.field_numbers(::Type{SimpleGate}) = (;mtype = 1, parameters = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimpleGate})
    mtype = GateType.GateID
    parameters = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, GateType.T)
        elseif field_number == 2
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimpleGate(mtype, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimpleGate)
    initpos = position(e.io)
    x.mtype != GateType.GateID && PB.encode(e, 1, x.mtype)
    !isempty(x.parameters) && PB.encode(e, 2, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimpleGate)
    encoded_size = 0
    x.mtype != GateType.GateID && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    return encoded_size
end

const SimpleKrausChannel = var"##Stub#SimpleKrausChannel"
PB.default_values(::Type{SimpleKrausChannel}) = (;mtype = KrausChannelType.ResetX, parameters = Vector{Arg}())
PB.field_numbers(::Type{SimpleKrausChannel}) = (;mtype = 1, parameters = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimpleKrausChannel})
    mtype = KrausChannelType.ResetX
    parameters = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, KrausChannelType.T)
        elseif field_number == 2
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimpleKrausChannel(mtype, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimpleKrausChannel)
    initpos = position(e.io)
    x.mtype != KrausChannelType.ResetX && PB.encode(e, 1, x.mtype)
    !isempty(x.parameters) && PB.encode(e, 2, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimpleKrausChannel)
    encoded_size = 0
    x.mtype != KrausChannelType.ResetX && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    return encoded_size
end

const SimpleOperation = var"##Stub#SimpleOperation"
PB.default_values(::Type{SimpleOperation}) = (;mtype = OperationType.MeasureX, parameters = Vector{Arg}())
PB.field_numbers(::Type{SimpleOperation}) = (;mtype = 1, parameters = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimpleOperation})
    mtype = OperationType.MeasureX
    parameters = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, OperationType.T)
        elseif field_number == 2
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimpleOperation(mtype, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimpleOperation)
    initpos = position(e.io)
    x.mtype != OperationType.MeasureX && PB.encode(e, 1, x.mtype)
    !isempty(x.parameters) && PB.encode(e, 2, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimpleOperation)
    encoded_size = 0
    x.mtype != OperationType.MeasureX && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    return encoded_size
end

const SimpleOperator = var"##Stub#SimpleOperator"
PB.default_values(::Type{SimpleOperator}) = (;mtype = OperatorType.SigmaMinus, parameters = Vector{Arg}())
PB.field_numbers(::Type{SimpleOperator}) = (;mtype = 1, parameters = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimpleOperator})
    mtype = OperatorType.SigmaMinus
    parameters = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            mtype = PB.decode(d, OperatorType.T)
        elseif field_number == 2
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimpleOperator(mtype, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimpleOperator)
    initpos = position(e.io)
    x.mtype != OperatorType.SigmaMinus && PB.encode(e, 1, x.mtype)
    !isempty(x.parameters) && PB.encode(e, 2, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimpleOperator)
    encoded_size = 0
    x.mtype != OperatorType.SigmaMinus && (encoded_size += PB._encoded_size(x.mtype, 1))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    return encoded_size
end

const Circuit = var"##Stub#Circuit"{var"##Stub#Operation",var"##Stub#Declaration"{var"##Stub#Operation"}}
PB.default_values(::Type{Circuit}) = (;instructions = Vector{Instruction}(), decls = Dict{UInt64,Declaration}(), declorder = Vector{UInt64}())
PB.field_numbers(::Type{Circuit}) = (;instructions = 1, decls = 2, declorder = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Circuit})
    instructions = PB.BufferedVector{Instruction}()
    decls = Dict{UInt64,Declaration}()
    declorder = PB.BufferedVector{UInt64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, instructions)
        elseif field_number == 2
            PB.decode!(d, decls)
        elseif field_number == 3
            PB.decode!(d, wire_type, declorder)
        else
            Base.skip(d, wire_type)
        end
    end
    return Circuit(instructions[], decls, declorder[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Circuit)
    initpos = position(e.io)
    !isempty(x.instructions) && PB.encode(e, 1, x.instructions)
    !isempty(x.decls) && PB.encode(e, 2, x.decls)
    !isempty(x.declorder) && PB.encode(e, 3, x.declorder)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Circuit)
    encoded_size = 0
    !isempty(x.instructions) && (encoded_size += PB._encoded_size(x.instructions, 1))
    !isempty(x.decls) && (encoded_size += PB._encoded_size(x.decls, 2))
    !isempty(x.declorder) && (encoded_size += PB._encoded_size(x.declorder, 3))
    return encoded_size
end

const Declaration = var"##Stub#Declaration"{var"##Stub#Operation"}
PB.oneof_field_types(::Type{Declaration}) = (;
    decl = (;gatedecl=GateDecl, block=Block),
)
PB.default_values(::Type{Declaration}) = (;gatedecl = nothing, block = nothing)
PB.field_numbers(::Type{Declaration}) = (;gatedecl = 1, block = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Declaration})
    decl = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            decl = OneOf(:gatedecl, PB.decode(d, Ref{GateDecl}))
        elseif field_number == 2
            decl = OneOf(:block, PB.decode(d, Ref{Block}))
        else
            Base.skip(d, wire_type)
        end
    end
    return Declaration(decl)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Declaration)
    initpos = position(e.io)
    if isnothing(x.decl);
    elseif x.decl.name === :gatedecl
        PB.encode(e, 1, x.decl[]::GateDecl)
    elseif x.decl.name === :block
        PB.encode(e, 2, x.decl[]::Block)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Declaration)
    encoded_size = 0
    if isnothing(x.decl);
    elseif x.decl.name === :gatedecl
        encoded_size += PB._encoded_size(x.decl[]::GateDecl, 1)
    elseif x.decl.name === :block
        encoded_size += PB._encoded_size(x.decl[]::Block, 2)
    end
    return encoded_size
end

const GateCall = var"##Stub#GateCall"{var"##Stub#Operation"}
PB.default_values(::Type{GateCall}) = (;decl = nothing, args = Vector{Arg}())
PB.field_numbers(::Type{GateCall}) = (;decl = 1, args = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GateCall})
    decl = Ref{Union{Nothing,GateDecl}}(nothing)
    args = PB.BufferedVector{Arg}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, decl)
        elseif field_number == 2
            PB.decode!(d, args)
        else
            Base.skip(d, wire_type)
        end
    end
    return GateCall(decl[], args[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GateCall)
    initpos = position(e.io)
    !isnothing(x.decl) && PB.encode(e, 1, x.decl)
    !isempty(x.args) && PB.encode(e, 2, x.args)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GateCall)
    encoded_size = 0
    !isnothing(x.decl) && (encoded_size += PB._encoded_size(x.decl, 1))
    !isempty(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    return encoded_size
end

const RescaledGate = var"##Stub#RescaledGate"{var"##Stub#Gate"{var"##Stub#Operation"}}
PB.default_values(::Type{RescaledGate}) = (;operation = nothing, scale = nothing)
PB.field_numbers(::Type{RescaledGate}) = (;operation = 1, scale = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RescaledGate})
    operation = Ref{Union{Nothing,Gate}}(nothing)
    scale = Ref{Union{Nothing,Arg}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, scale)
        else
            Base.skip(d, wire_type)
        end
    end
    return RescaledGate(operation[], scale[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RescaledGate)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isnothing(x.scale) && PB.encode(e, 2, x.scale)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RescaledGate)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isnothing(x.scale) && (encoded_size += PB._encoded_size(x.scale, 2))
    return encoded_size
end

const KrausChannel = var"##Stub#KrausChannel"{var"##Stub#Operator"{var"##Stub#Operation"},var"##Stub#Gate"{var"##Stub#Operation"}}
PB.oneof_field_types(::Type{KrausChannel}) = (;
    krauschannel = (;simplekrauschannel=SimpleKrausChannel, customkrauschannel=CustomKrausChannel, depolarizingchannel=DepolarizingChannel, mixedunitarychannel=MixedUnitaryChannel, paulichannel=PauliChannel),
)
PB.default_values(::Type{KrausChannel}) = (;simplekrauschannel = nothing, customkrauschannel = nothing, depolarizingchannel = nothing, mixedunitarychannel = nothing, paulichannel = nothing)
PB.field_numbers(::Type{KrausChannel}) = (;simplekrauschannel = 1, customkrauschannel = 2, depolarizingchannel = 3, mixedunitarychannel = 4, paulichannel = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:KrausChannel})
    krauschannel = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            krauschannel = OneOf(:simplekrauschannel, PB.decode(d, Ref{SimpleKrausChannel}))
        elseif field_number == 2
            krauschannel = OneOf(:customkrauschannel, PB.decode(d, Ref{CustomKrausChannel}))
        elseif field_number == 3
            krauschannel = OneOf(:depolarizingchannel, PB.decode(d, Ref{DepolarizingChannel}))
        elseif field_number == 4
            krauschannel = OneOf(:mixedunitarychannel, PB.decode(d, Ref{MixedUnitaryChannel}))
        elseif field_number == 5
            krauschannel = OneOf(:paulichannel, PB.decode(d, Ref{PauliChannel}))
        else
            Base.skip(d, wire_type)
        end
    end
    return KrausChannel(krauschannel)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::KrausChannel)
    initpos = position(e.io)
    if isnothing(x.krauschannel);
    elseif x.krauschannel.name === :simplekrauschannel
        PB.encode(e, 1, x.krauschannel[]::SimpleKrausChannel)
    elseif x.krauschannel.name === :customkrauschannel
        PB.encode(e, 2, x.krauschannel[]::CustomKrausChannel)
    elseif x.krauschannel.name === :depolarizingchannel
        PB.encode(e, 3, x.krauschannel[]::DepolarizingChannel)
    elseif x.krauschannel.name === :mixedunitarychannel
        PB.encode(e, 4, x.krauschannel[]::MixedUnitaryChannel)
    elseif x.krauschannel.name === :paulichannel
        PB.encode(e, 5, x.krauschannel[]::PauliChannel)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::KrausChannel)
    encoded_size = 0
    if isnothing(x.krauschannel);
    elseif x.krauschannel.name === :simplekrauschannel
        encoded_size += PB._encoded_size(x.krauschannel[]::SimpleKrausChannel, 1)
    elseif x.krauschannel.name === :customkrauschannel
        encoded_size += PB._encoded_size(x.krauschannel[]::CustomKrausChannel, 2)
    elseif x.krauschannel.name === :depolarizingchannel
        encoded_size += PB._encoded_size(x.krauschannel[]::DepolarizingChannel, 3)
    elseif x.krauschannel.name === :mixedunitarychannel
        encoded_size += PB._encoded_size(x.krauschannel[]::MixedUnitaryChannel, 4)
    elseif x.krauschannel.name === :paulichannel
        encoded_size += PB._encoded_size(x.krauschannel[]::PauliChannel, 5)
    end
    return encoded_size
end

const Gate = var"##Stub#Gate"{var"##Stub#Operation"}
PB.oneof_field_types(::Type{Gate}) = (;
    gate = (;simplegate=SimpleGate, customgate=CustomGate, generalized=Generalized, control=Control, power=Power, inverse=Inverse, parallel=Parallel, gatecall=GateCall, paulistring=pauli_pb.PauliString, cachedgatecall=CachedGateCall, rpauli=RPauli),
)
PB.default_values(::Type{Gate}) = (;simplegate = nothing, customgate = nothing, generalized = nothing, control = nothing, power = nothing, inverse = nothing, parallel = nothing, gatecall = nothing, paulistring = nothing, cachedgatecall = nothing, rpauli = nothing)
PB.field_numbers(::Type{Gate}) = (;simplegate = 1, customgate = 2, generalized = 3, control = 4, power = 5, inverse = 6, parallel = 7, gatecall = 8, paulistring = 9, cachedgatecall = 10, rpauli = 11)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Gate})
    gate = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            gate = OneOf(:simplegate, PB.decode(d, Ref{SimpleGate}))
        elseif field_number == 2
            gate = OneOf(:customgate, PB.decode(d, Ref{CustomGate}))
        elseif field_number == 3
            gate = OneOf(:generalized, PB.decode(d, Ref{Generalized}))
        elseif field_number == 4
            gate = OneOf(:control, PB.decode(d, Ref{Control}))
        elseif field_number == 5
            gate = OneOf(:power, PB.decode(d, Ref{Power}))
        elseif field_number == 6
            gate = OneOf(:inverse, PB.decode(d, Ref{Inverse}))
        elseif field_number == 7
            gate = OneOf(:parallel, PB.decode(d, Ref{Parallel}))
        elseif field_number == 8
            gate = OneOf(:gatecall, PB.decode(d, Ref{GateCall}))
        elseif field_number == 9
            gate = OneOf(:paulistring, PB.decode(d, Ref{pauli_pb.PauliString}))
        elseif field_number == 10
            gate = OneOf(:cachedgatecall, PB.decode(d, Ref{CachedGateCall}))
        elseif field_number == 11
            gate = OneOf(:rpauli, PB.decode(d, Ref{RPauli}))
        else
            Base.skip(d, wire_type)
        end
    end
    return Gate(gate)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Gate)
    initpos = position(e.io)
    if isnothing(x.gate);
    elseif x.gate.name === :simplegate
        PB.encode(e, 1, x.gate[]::SimpleGate)
    elseif x.gate.name === :customgate
        PB.encode(e, 2, x.gate[]::CustomGate)
    elseif x.gate.name === :generalized
        PB.encode(e, 3, x.gate[]::Generalized)
    elseif x.gate.name === :control
        PB.encode(e, 4, x.gate[]::Control)
    elseif x.gate.name === :power
        PB.encode(e, 5, x.gate[]::Power)
    elseif x.gate.name === :inverse
        PB.encode(e, 6, x.gate[]::Inverse)
    elseif x.gate.name === :parallel
        PB.encode(e, 7, x.gate[]::Parallel)
    elseif x.gate.name === :gatecall
        PB.encode(e, 8, x.gate[]::GateCall)
    elseif x.gate.name === :paulistring
        PB.encode(e, 9, x.gate[]::pauli_pb.PauliString)
    elseif x.gate.name === :cachedgatecall
        PB.encode(e, 10, x.gate[]::CachedGateCall)
    elseif x.gate.name === :rpauli
        PB.encode(e, 11, x.gate[]::RPauli)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Gate)
    encoded_size = 0
    if isnothing(x.gate);
    elseif x.gate.name === :simplegate
        encoded_size += PB._encoded_size(x.gate[]::SimpleGate, 1)
    elseif x.gate.name === :customgate
        encoded_size += PB._encoded_size(x.gate[]::CustomGate, 2)
    elseif x.gate.name === :generalized
        encoded_size += PB._encoded_size(x.gate[]::Generalized, 3)
    elseif x.gate.name === :control
        encoded_size += PB._encoded_size(x.gate[]::Control, 4)
    elseif x.gate.name === :power
        encoded_size += PB._encoded_size(x.gate[]::Power, 5)
    elseif x.gate.name === :inverse
        encoded_size += PB._encoded_size(x.gate[]::Inverse, 6)
    elseif x.gate.name === :parallel
        encoded_size += PB._encoded_size(x.gate[]::Parallel, 7)
    elseif x.gate.name === :gatecall
        encoded_size += PB._encoded_size(x.gate[]::GateCall, 8)
    elseif x.gate.name === :paulistring
        encoded_size += PB._encoded_size(x.gate[]::pauli_pb.PauliString, 9)
    elseif x.gate.name === :cachedgatecall
        encoded_size += PB._encoded_size(x.gate[]::CachedGateCall, 10)
    elseif x.gate.name === :rpauli
        encoded_size += PB._encoded_size(x.gate[]::RPauli, 11)
    end
    return encoded_size
end

const Operator = var"##Stub#Operator"{var"##Stub#Operation"}
PB.oneof_field_types(::Type{Operator}) = (;
    operator = (;simplegate=SimpleGate, customgate=CustomGate, generalized=Generalized, control=Control, power=Power, inverse=Inverse, parallel=Parallel, gatecall=GateCall, paulistring=pauli_pb.PauliString, simpleoperator=SimpleOperator, customoperator=CustomOperator, rescaledgate=RescaledGate, cachedgatecall=CachedGateCall, rpauli=RPauli),
)
PB.default_values(::Type{Operator}) = (;simplegate = nothing, customgate = nothing, generalized = nothing, control = nothing, power = nothing, inverse = nothing, parallel = nothing, gatecall = nothing, paulistring = nothing, simpleoperator = nothing, customoperator = nothing, rescaledgate = nothing, cachedgatecall = nothing, rpauli = nothing)
PB.field_numbers(::Type{Operator}) = (;simplegate = 1, customgate = 2, generalized = 3, control = 4, power = 5, inverse = 6, parallel = 7, gatecall = 8, paulistring = 9, simpleoperator = 10, customoperator = 11, rescaledgate = 12, cachedgatecall = 13, rpauli = 14)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Operator})
    operator = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            operator = OneOf(:simplegate, PB.decode(d, Ref{SimpleGate}))
        elseif field_number == 2
            operator = OneOf(:customgate, PB.decode(d, Ref{CustomGate}))
        elseif field_number == 3
            operator = OneOf(:generalized, PB.decode(d, Ref{Generalized}))
        elseif field_number == 4
            operator = OneOf(:control, PB.decode(d, Ref{Control}))
        elseif field_number == 5
            operator = OneOf(:power, PB.decode(d, Ref{Power}))
        elseif field_number == 6
            operator = OneOf(:inverse, PB.decode(d, Ref{Inverse}))
        elseif field_number == 7
            operator = OneOf(:parallel, PB.decode(d, Ref{Parallel}))
        elseif field_number == 8
            operator = OneOf(:gatecall, PB.decode(d, Ref{GateCall}))
        elseif field_number == 9
            operator = OneOf(:paulistring, PB.decode(d, Ref{pauli_pb.PauliString}))
        elseif field_number == 10
            operator = OneOf(:simpleoperator, PB.decode(d, Ref{SimpleOperator}))
        elseif field_number == 11
            operator = OneOf(:customoperator, PB.decode(d, Ref{CustomOperator}))
        elseif field_number == 12
            operator = OneOf(:rescaledgate, PB.decode(d, Ref{RescaledGate}))
        elseif field_number == 13
            operator = OneOf(:cachedgatecall, PB.decode(d, Ref{CachedGateCall}))
        elseif field_number == 14
            operator = OneOf(:rpauli, PB.decode(d, Ref{RPauli}))
        else
            Base.skip(d, wire_type)
        end
    end
    return Operator(operator)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Operator)
    initpos = position(e.io)
    if isnothing(x.operator);
    elseif x.operator.name === :simplegate
        PB.encode(e, 1, x.operator[]::SimpleGate)
    elseif x.operator.name === :customgate
        PB.encode(e, 2, x.operator[]::CustomGate)
    elseif x.operator.name === :generalized
        PB.encode(e, 3, x.operator[]::Generalized)
    elseif x.operator.name === :control
        PB.encode(e, 4, x.operator[]::Control)
    elseif x.operator.name === :power
        PB.encode(e, 5, x.operator[]::Power)
    elseif x.operator.name === :inverse
        PB.encode(e, 6, x.operator[]::Inverse)
    elseif x.operator.name === :parallel
        PB.encode(e, 7, x.operator[]::Parallel)
    elseif x.operator.name === :gatecall
        PB.encode(e, 8, x.operator[]::GateCall)
    elseif x.operator.name === :paulistring
        PB.encode(e, 9, x.operator[]::pauli_pb.PauliString)
    elseif x.operator.name === :simpleoperator
        PB.encode(e, 10, x.operator[]::SimpleOperator)
    elseif x.operator.name === :customoperator
        PB.encode(e, 11, x.operator[]::CustomOperator)
    elseif x.operator.name === :rescaledgate
        PB.encode(e, 12, x.operator[]::RescaledGate)
    elseif x.operator.name === :cachedgatecall
        PB.encode(e, 13, x.operator[]::CachedGateCall)
    elseif x.operator.name === :rpauli
        PB.encode(e, 14, x.operator[]::RPauli)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Operator)
    encoded_size = 0
    if isnothing(x.operator);
    elseif x.operator.name === :simplegate
        encoded_size += PB._encoded_size(x.operator[]::SimpleGate, 1)
    elseif x.operator.name === :customgate
        encoded_size += PB._encoded_size(x.operator[]::CustomGate, 2)
    elseif x.operator.name === :generalized
        encoded_size += PB._encoded_size(x.operator[]::Generalized, 3)
    elseif x.operator.name === :control
        encoded_size += PB._encoded_size(x.operator[]::Control, 4)
    elseif x.operator.name === :power
        encoded_size += PB._encoded_size(x.operator[]::Power, 5)
    elseif x.operator.name === :inverse
        encoded_size += PB._encoded_size(x.operator[]::Inverse, 6)
    elseif x.operator.name === :parallel
        encoded_size += PB._encoded_size(x.operator[]::Parallel, 7)
    elseif x.operator.name === :gatecall
        encoded_size += PB._encoded_size(x.operator[]::GateCall, 8)
    elseif x.operator.name === :paulistring
        encoded_size += PB._encoded_size(x.operator[]::pauli_pb.PauliString, 9)
    elseif x.operator.name === :simpleoperator
        encoded_size += PB._encoded_size(x.operator[]::SimpleOperator, 10)
    elseif x.operator.name === :customoperator
        encoded_size += PB._encoded_size(x.operator[]::CustomOperator, 11)
    elseif x.operator.name === :rescaledgate
        encoded_size += PB._encoded_size(x.operator[]::RescaledGate, 12)
    elseif x.operator.name === :cachedgatecall
        encoded_size += PB._encoded_size(x.operator[]::CachedGateCall, 13)
    elseif x.operator.name === :rpauli
        encoded_size += PB._encoded_size(x.operator[]::RPauli, 14)
    end
    return encoded_size
end

const Operation = var"##Stub#Operation"
PB.oneof_field_types(::Type{Operation}) = (;
    operation = (;simplegate=SimpleGate, customgate=CustomGate, generalized=Generalized, control=Control, power=Power, inverse=Inverse, parallel=Parallel, gatecall=GateCall, paulistring=pauli_pb.PauliString, simplekrauschannel=SimpleKrausChannel, customkrauschannel=CustomKrausChannel, depolarizingchannel=DepolarizingChannel, mixedunitarychannel=MixedUnitaryChannel, paulichannel=PauliChannel, simpleoperator=SimpleOperator, customoperator=CustomOperator, rescaledgate=RescaledGate, simpleoperation=SimpleOperation, ifstatement=IfStatement, generalizedoperation=GeneralizedOperation, amplitude=Amplitude, expectationvalue=ExpectationValue, simpleannotation=SimpleAnnotation, generalizedannotation=GeneralizedAnnotation, cachedgatecall=CachedGateCall, rpauli=RPauli, repeat=Repeat, block=Block, readouterr=ReadoutErr),
)
PB.default_values(::Type{Operation}) = (;simplegate = nothing, customgate = nothing, generalized = nothing, control = nothing, power = nothing, inverse = nothing, parallel = nothing, gatecall = nothing, paulistring = nothing, simplekrauschannel = nothing, customkrauschannel = nothing, depolarizingchannel = nothing, mixedunitarychannel = nothing, paulichannel = nothing, simpleoperator = nothing, customoperator = nothing, rescaledgate = nothing, simpleoperation = nothing, ifstatement = nothing, generalizedoperation = nothing, amplitude = nothing, expectationvalue = nothing, simpleannotation = nothing, generalizedannotation = nothing, cachedgatecall = nothing, rpauli = nothing, repeat = nothing, block = nothing, readouterr = nothing)
PB.field_numbers(::Type{Operation}) = (;simplegate = 1, customgate = 2, generalized = 3, control = 4, power = 5, inverse = 6, parallel = 7, gatecall = 8, paulistring = 9, simplekrauschannel = 10, customkrauschannel = 11, depolarizingchannel = 12, mixedunitarychannel = 13, paulichannel = 14, simpleoperator = 15, customoperator = 16, rescaledgate = 17, simpleoperation = 18, ifstatement = 19, generalizedoperation = 20, amplitude = 21, expectationvalue = 22, simpleannotation = 23, generalizedannotation = 24, cachedgatecall = 25, rpauli = 26, repeat = 27, block = 28, readouterr = 29)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Operation})
    operation = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            operation = OneOf(:simplegate, PB.decode(d, Ref{SimpleGate}))
        elseif field_number == 2
            operation = OneOf(:customgate, PB.decode(d, Ref{CustomGate}))
        elseif field_number == 3
            operation = OneOf(:generalized, PB.decode(d, Ref{Generalized}))
        elseif field_number == 4
            operation = OneOf(:control, PB.decode(d, Ref{Control}))
        elseif field_number == 5
            operation = OneOf(:power, PB.decode(d, Ref{Power}))
        elseif field_number == 6
            operation = OneOf(:inverse, PB.decode(d, Ref{Inverse}))
        elseif field_number == 7
            operation = OneOf(:parallel, PB.decode(d, Ref{Parallel}))
        elseif field_number == 8
            operation = OneOf(:gatecall, PB.decode(d, Ref{GateCall}))
        elseif field_number == 9
            operation = OneOf(:paulistring, PB.decode(d, Ref{pauli_pb.PauliString}))
        elseif field_number == 10
            operation = OneOf(:simplekrauschannel, PB.decode(d, Ref{SimpleKrausChannel}))
        elseif field_number == 11
            operation = OneOf(:customkrauschannel, PB.decode(d, Ref{CustomKrausChannel}))
        elseif field_number == 12
            operation = OneOf(:depolarizingchannel, PB.decode(d, Ref{DepolarizingChannel}))
        elseif field_number == 13
            operation = OneOf(:mixedunitarychannel, PB.decode(d, Ref{MixedUnitaryChannel}))
        elseif field_number == 14
            operation = OneOf(:paulichannel, PB.decode(d, Ref{PauliChannel}))
        elseif field_number == 15
            operation = OneOf(:simpleoperator, PB.decode(d, Ref{SimpleOperator}))
        elseif field_number == 16
            operation = OneOf(:customoperator, PB.decode(d, Ref{CustomOperator}))
        elseif field_number == 17
            operation = OneOf(:rescaledgate, PB.decode(d, Ref{RescaledGate}))
        elseif field_number == 18
            operation = OneOf(:simpleoperation, PB.decode(d, Ref{SimpleOperation}))
        elseif field_number == 19
            operation = OneOf(:ifstatement, PB.decode(d, Ref{IfStatement}))
        elseif field_number == 20
            operation = OneOf(:generalizedoperation, PB.decode(d, Ref{GeneralizedOperation}))
        elseif field_number == 21
            operation = OneOf(:amplitude, PB.decode(d, Ref{Amplitude}))
        elseif field_number == 22
            operation = OneOf(:expectationvalue, PB.decode(d, Ref{ExpectationValue}))
        elseif field_number == 23
            operation = OneOf(:simpleannotation, PB.decode(d, Ref{SimpleAnnotation}))
        elseif field_number == 24
            operation = OneOf(:generalizedannotation, PB.decode(d, Ref{GeneralizedAnnotation}))
        elseif field_number == 25
            operation = OneOf(:cachedgatecall, PB.decode(d, Ref{CachedGateCall}))
        elseif field_number == 26
            operation = OneOf(:rpauli, PB.decode(d, Ref{RPauli}))
        elseif field_number == 27
            operation = OneOf(:repeat, PB.decode(d, Ref{Repeat}))
        elseif field_number == 28
            operation = OneOf(:block, PB.decode(d, Ref{Block}))
        elseif field_number == 29
            operation = OneOf(:readouterr, PB.decode(d, Ref{ReadoutErr}))
        else
            Base.skip(d, wire_type)
        end
    end
    return Operation(operation)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Operation)
    initpos = position(e.io)
    if isnothing(x.operation);
    elseif x.operation.name === :simplegate
        PB.encode(e, 1, x.operation[]::SimpleGate)
    elseif x.operation.name === :customgate
        PB.encode(e, 2, x.operation[]::CustomGate)
    elseif x.operation.name === :generalized
        PB.encode(e, 3, x.operation[]::Generalized)
    elseif x.operation.name === :control
        PB.encode(e, 4, x.operation[]::Control)
    elseif x.operation.name === :power
        PB.encode(e, 5, x.operation[]::Power)
    elseif x.operation.name === :inverse
        PB.encode(e, 6, x.operation[]::Inverse)
    elseif x.operation.name === :parallel
        PB.encode(e, 7, x.operation[]::Parallel)
    elseif x.operation.name === :gatecall
        PB.encode(e, 8, x.operation[]::GateCall)
    elseif x.operation.name === :paulistring
        PB.encode(e, 9, x.operation[]::pauli_pb.PauliString)
    elseif x.operation.name === :simplekrauschannel
        PB.encode(e, 10, x.operation[]::SimpleKrausChannel)
    elseif x.operation.name === :customkrauschannel
        PB.encode(e, 11, x.operation[]::CustomKrausChannel)
    elseif x.operation.name === :depolarizingchannel
        PB.encode(e, 12, x.operation[]::DepolarizingChannel)
    elseif x.operation.name === :mixedunitarychannel
        PB.encode(e, 13, x.operation[]::MixedUnitaryChannel)
    elseif x.operation.name === :paulichannel
        PB.encode(e, 14, x.operation[]::PauliChannel)
    elseif x.operation.name === :simpleoperator
        PB.encode(e, 15, x.operation[]::SimpleOperator)
    elseif x.operation.name === :customoperator
        PB.encode(e, 16, x.operation[]::CustomOperator)
    elseif x.operation.name === :rescaledgate
        PB.encode(e, 17, x.operation[]::RescaledGate)
    elseif x.operation.name === :simpleoperation
        PB.encode(e, 18, x.operation[]::SimpleOperation)
    elseif x.operation.name === :ifstatement
        PB.encode(e, 19, x.operation[]::IfStatement)
    elseif x.operation.name === :generalizedoperation
        PB.encode(e, 20, x.operation[]::GeneralizedOperation)
    elseif x.operation.name === :amplitude
        PB.encode(e, 21, x.operation[]::Amplitude)
    elseif x.operation.name === :expectationvalue
        PB.encode(e, 22, x.operation[]::ExpectationValue)
    elseif x.operation.name === :simpleannotation
        PB.encode(e, 23, x.operation[]::SimpleAnnotation)
    elseif x.operation.name === :generalizedannotation
        PB.encode(e, 24, x.operation[]::GeneralizedAnnotation)
    elseif x.operation.name === :cachedgatecall
        PB.encode(e, 25, x.operation[]::CachedGateCall)
    elseif x.operation.name === :rpauli
        PB.encode(e, 26, x.operation[]::RPauli)
    elseif x.operation.name === :repeat
        PB.encode(e, 27, x.operation[]::Repeat)
    elseif x.operation.name === :block
        PB.encode(e, 28, x.operation[]::Block)
    elseif x.operation.name === :readouterr
        PB.encode(e, 29, x.operation[]::ReadoutErr)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::Operation)
    encoded_size = 0
    if isnothing(x.operation);
    elseif x.operation.name === :simplegate
        encoded_size += PB._encoded_size(x.operation[]::SimpleGate, 1)
    elseif x.operation.name === :customgate
        encoded_size += PB._encoded_size(x.operation[]::CustomGate, 2)
    elseif x.operation.name === :generalized
        encoded_size += PB._encoded_size(x.operation[]::Generalized, 3)
    elseif x.operation.name === :control
        encoded_size += PB._encoded_size(x.operation[]::Control, 4)
    elseif x.operation.name === :power
        encoded_size += PB._encoded_size(x.operation[]::Power, 5)
    elseif x.operation.name === :inverse
        encoded_size += PB._encoded_size(x.operation[]::Inverse, 6)
    elseif x.operation.name === :parallel
        encoded_size += PB._encoded_size(x.operation[]::Parallel, 7)
    elseif x.operation.name === :gatecall
        encoded_size += PB._encoded_size(x.operation[]::GateCall, 8)
    elseif x.operation.name === :paulistring
        encoded_size += PB._encoded_size(x.operation[]::pauli_pb.PauliString, 9)
    elseif x.operation.name === :simplekrauschannel
        encoded_size += PB._encoded_size(x.operation[]::SimpleKrausChannel, 10)
    elseif x.operation.name === :customkrauschannel
        encoded_size += PB._encoded_size(x.operation[]::CustomKrausChannel, 11)
    elseif x.operation.name === :depolarizingchannel
        encoded_size += PB._encoded_size(x.operation[]::DepolarizingChannel, 12)
    elseif x.operation.name === :mixedunitarychannel
        encoded_size += PB._encoded_size(x.operation[]::MixedUnitaryChannel, 13)
    elseif x.operation.name === :paulichannel
        encoded_size += PB._encoded_size(x.operation[]::PauliChannel, 14)
    elseif x.operation.name === :simpleoperator
        encoded_size += PB._encoded_size(x.operation[]::SimpleOperator, 15)
    elseif x.operation.name === :customoperator
        encoded_size += PB._encoded_size(x.operation[]::CustomOperator, 16)
    elseif x.operation.name === :rescaledgate
        encoded_size += PB._encoded_size(x.operation[]::RescaledGate, 17)
    elseif x.operation.name === :simpleoperation
        encoded_size += PB._encoded_size(x.operation[]::SimpleOperation, 18)
    elseif x.operation.name === :ifstatement
        encoded_size += PB._encoded_size(x.operation[]::IfStatement, 19)
    elseif x.operation.name === :generalizedoperation
        encoded_size += PB._encoded_size(x.operation[]::GeneralizedOperation, 20)
    elseif x.operation.name === :amplitude
        encoded_size += PB._encoded_size(x.operation[]::Amplitude, 21)
    elseif x.operation.name === :expectationvalue
        encoded_size += PB._encoded_size(x.operation[]::ExpectationValue, 22)
    elseif x.operation.name === :simpleannotation
        encoded_size += PB._encoded_size(x.operation[]::SimpleAnnotation, 23)
    elseif x.operation.name === :generalizedannotation
        encoded_size += PB._encoded_size(x.operation[]::GeneralizedAnnotation, 24)
    elseif x.operation.name === :cachedgatecall
        encoded_size += PB._encoded_size(x.operation[]::CachedGateCall, 25)
    elseif x.operation.name === :rpauli
        encoded_size += PB._encoded_size(x.operation[]::RPauli, 26)
    elseif x.operation.name === :repeat
        encoded_size += PB._encoded_size(x.operation[]::Repeat, 27)
    elseif x.operation.name === :block
        encoded_size += PB._encoded_size(x.operation[]::Block, 28)
    elseif x.operation.name === :readouterr
        encoded_size += PB._encoded_size(x.operation[]::ReadoutErr, 29)
    end
    return encoded_size
end
end # module
