# Autogenerated using ProtoBuf.jl v1.2.3


module hamiltonian_pb


import ..pauli_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export HamiltonianTerm, Hamiltonian


struct HamiltonianTerm
    coefficient::Float64
    pauli::Union{Nothing,pauli_pb.PauliString}
    qubits::Vector{Int64}
end
PB.default_values(::Type{HamiltonianTerm}) = (;coefficient = zero(Float64), pauli = nothing, qubits = Vector{Int64}())
PB.field_numbers(::Type{HamiltonianTerm}) = (;coefficient = 1, pauli = 2, qubits = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:HamiltonianTerm})
    coefficient = zero(Float64)
    pauli = Ref{Union{Nothing,pauli_pb.PauliString}}(nothing)
    qubits = PB.BufferedVector{Int64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            coefficient = PB.decode(d, Float64)
        elseif field_number == 2
            PB.decode!(d, pauli)
        elseif field_number == 3
            PB.decode!(d, wire_type, qubits)
        else
            Base.skip(d, wire_type)
        end
    end
    return HamiltonianTerm(coefficient, pauli[], qubits[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::HamiltonianTerm)
    initpos = position(e.io)
    x.coefficient !== zero(Float64) && PB.encode(e, 1, x.coefficient)
    !isnothing(x.pauli) && PB.encode(e, 2, x.pauli)
    !isempty(x.qubits) && PB.encode(e, 3, x.qubits)
    return position(e.io) - initpos
end
function PB._encoded_size(x::HamiltonianTerm)
    encoded_size = 0
    x.coefficient !== zero(Float64) && (encoded_size += PB._encoded_size(x.coefficient, 1))
    !isnothing(x.pauli) && (encoded_size += PB._encoded_size(x.pauli, 2))
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 3))
    return encoded_size
end

struct Hamiltonian
    terms::Vector{HamiltonianTerm}
end
PB.default_values(::Type{Hamiltonian}) = (;terms = Vector{HamiltonianTerm}())
PB.field_numbers(::Type{Hamiltonian}) = (;terms = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Hamiltonian})
    terms = PB.BufferedVector{HamiltonianTerm}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, terms)
        else
            Base.skip(d, wire_type)
        end
    end
    return Hamiltonian(terms[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Hamiltonian)
    initpos = position(e.io)
    !isempty(x.terms) && PB.encode(e, 1, x.terms)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Hamiltonian)
    encoded_size = 0
    !isempty(x.terms) && (encoded_size += PB._encoded_size(x.terms, 1))
    return encoded_size
end
end # module