# Autogenerated using ProtoBuf.jl v1.2.3


module noisemodel_pb


import ..circuit_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ExactQubitReadoutNoise, CustomNoiseRule, SetOperationInstanceQubitNoise
export ExactOperationInstanceQubitNoise, SymbolicPattern, OperationInstanceNoise
export SetQubitReadoutNoise, GlobalReadoutNoise, IdleNoise, SetIdleQubitNoise, NoiseRule
export NoiseModel


struct ExactQubitReadoutNoise
    qubits::Vector{UInt32}
    noise::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{ExactQubitReadoutNoise}) = (;qubits = Vector{UInt32}(), noise = nothing)
PB.field_numbers(::Type{ExactQubitReadoutNoise}) = (;qubits = 1, noise = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExactQubitReadoutNoise})
    qubits = PB.BufferedVector{UInt32}()
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, qubits)
        elseif field_number == 2
            PB.decode!(d, noise)
        else
            Base.skip(d, wire_type)
        end
    end
    return ExactQubitReadoutNoise(qubits[], noise[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExactQubitReadoutNoise)
    initpos = position(e.io)
    !isempty(x.qubits) && PB.encode(e, 1, x.qubits)
    !isnothing(x.noise) && PB.encode(e, 2, x.noise)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExactQubitReadoutNoise)
    encoded_size = 0
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 1))
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 2))
    return encoded_size
end

struct CustomNoiseRule
    matcher::String
    generator::String
    priority::Int32
    before::Bool
    replace::Bool
end
PB.default_values(::Type{CustomNoiseRule}) = (;matcher = "", generator = "", priority = zero(Int32), before = false, replace = false)
PB.field_numbers(::Type{CustomNoiseRule}) = (;matcher = 1, generator = 2, priority = 3, before = 4, replace = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CustomNoiseRule})
    matcher = ""
    generator = ""
    priority = zero(Int32)
    before = false
    replace = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            matcher = PB.decode(d, String)
        elseif field_number == 2
            generator = PB.decode(d, String)
        elseif field_number == 3
            priority = PB.decode(d, Int32)
        elseif field_number == 4
            before = PB.decode(d, Bool)
        elseif field_number == 5
            replace = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return CustomNoiseRule(matcher, generator, priority, before, replace)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CustomNoiseRule)
    initpos = position(e.io)
    !isempty(x.matcher) && PB.encode(e, 1, x.matcher)
    !isempty(x.generator) && PB.encode(e, 2, x.generator)
    x.priority != zero(Int32) && PB.encode(e, 3, x.priority)
    x.before != false && PB.encode(e, 4, x.before)
    x.replace != false && PB.encode(e, 5, x.replace)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CustomNoiseRule)
    encoded_size = 0
    !isempty(x.matcher) && (encoded_size += PB._encoded_size(x.matcher, 1))
    !isempty(x.generator) && (encoded_size += PB._encoded_size(x.generator, 2))
    x.priority != zero(Int32) && (encoded_size += PB._encoded_size(x.priority, 3))
    x.before != false && (encoded_size += PB._encoded_size(x.before, 4))
    x.replace != false && (encoded_size += PB._encoded_size(x.replace, 5))
    return encoded_size
end

struct SetOperationInstanceQubitNoise
    operation::Union{Nothing,circuit_pb.Operation}
    qubits::Vector{UInt32}
    noise::Union{Nothing,circuit_pb.Operation}
    before::Bool
    replace::Bool
end
PB.default_values(::Type{SetOperationInstanceQubitNoise}) = (;operation = nothing, qubits = Vector{UInt32}(), noise = nothing, before = false, replace = false)
PB.field_numbers(::Type{SetOperationInstanceQubitNoise}) = (;operation = 1, qubits = 2, noise = 3, before = 4, replace = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetOperationInstanceQubitNoise})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    qubits = PB.BufferedVector{UInt32}()
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    before = false
    replace = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, wire_type, qubits)
        elseif field_number == 3
            PB.decode!(d, noise)
        elseif field_number == 4
            before = PB.decode(d, Bool)
        elseif field_number == 5
            replace = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetOperationInstanceQubitNoise(operation[], qubits[], noise[], before, replace)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetOperationInstanceQubitNoise)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isempty(x.qubits) && PB.encode(e, 2, x.qubits)
    !isnothing(x.noise) && PB.encode(e, 3, x.noise)
    x.before != false && PB.encode(e, 4, x.before)
    x.replace != false && PB.encode(e, 5, x.replace)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetOperationInstanceQubitNoise)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 2))
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 3))
    x.before != false && (encoded_size += PB._encoded_size(x.before, 4))
    x.replace != false && (encoded_size += PB._encoded_size(x.replace, 5))
    return encoded_size
end

struct ExactOperationInstanceQubitNoise
    operation::Union{Nothing,circuit_pb.Operation}
    qubits::Vector{UInt32}
    noise::Union{Nothing,circuit_pb.Operation}
    before::Bool
    replace::Bool
end
PB.default_values(::Type{ExactOperationInstanceQubitNoise}) = (;operation = nothing, qubits = Vector{UInt32}(), noise = nothing, before = false, replace = false)
PB.field_numbers(::Type{ExactOperationInstanceQubitNoise}) = (;operation = 1, qubits = 2, noise = 3, before = 4, replace = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExactOperationInstanceQubitNoise})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    qubits = PB.BufferedVector{UInt32}()
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    before = false
    replace = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, wire_type, qubits)
        elseif field_number == 3
            PB.decode!(d, noise)
        elseif field_number == 4
            before = PB.decode(d, Bool)
        elseif field_number == 5
            replace = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return ExactOperationInstanceQubitNoise(operation[], qubits[], noise[], before, replace)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExactOperationInstanceQubitNoise)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isempty(x.qubits) && PB.encode(e, 2, x.qubits)
    !isnothing(x.noise) && PB.encode(e, 3, x.noise)
    x.before != false && PB.encode(e, 4, x.before)
    x.replace != false && PB.encode(e, 5, x.replace)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExactOperationInstanceQubitNoise)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 2))
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 3))
    x.before != false && (encoded_size += PB._encoded_size(x.before, 4))
    x.replace != false && (encoded_size += PB._encoded_size(x.replace, 5))
    return encoded_size
end

struct SymbolicPattern
    variables::Vector{circuit_pb.Arg}
    operation::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{SymbolicPattern}) = (;variables = Vector{circuit_pb.Arg}(), operation = nothing)
PB.field_numbers(::Type{SymbolicPattern}) = (;variables = 1, operation = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SymbolicPattern})
    variables = PB.BufferedVector{circuit_pb.Arg}()
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, variables)
        elseif field_number == 2
            PB.decode!(d, operation)
        else
            Base.skip(d, wire_type)
        end
    end
    return SymbolicPattern(variables[], operation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SymbolicPattern)
    initpos = position(e.io)
    !isempty(x.variables) && PB.encode(e, 1, x.variables)
    !isnothing(x.operation) && PB.encode(e, 2, x.operation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SymbolicPattern)
    encoded_size = 0
    !isempty(x.variables) && (encoded_size += PB._encoded_size(x.variables, 1))
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 2))
    return encoded_size
end

struct OperationInstanceNoise
    operation::Union{Nothing,circuit_pb.Operation}
    noise::Union{Nothing,circuit_pb.Operation}
    before::Bool
    replace::Bool
end
PB.default_values(::Type{OperationInstanceNoise}) = (;operation = nothing, noise = nothing, before = false, replace = false)
PB.field_numbers(::Type{OperationInstanceNoise}) = (;operation = 1, noise = 2, before = 3, replace = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OperationInstanceNoise})
    operation = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    before = false
    replace = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, operation)
        elseif field_number == 2
            PB.decode!(d, noise)
        elseif field_number == 3
            before = PB.decode(d, Bool)
        elseif field_number == 4
            replace = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return OperationInstanceNoise(operation[], noise[], before, replace)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OperationInstanceNoise)
    initpos = position(e.io)
    !isnothing(x.operation) && PB.encode(e, 1, x.operation)
    !isnothing(x.noise) && PB.encode(e, 2, x.noise)
    x.before != false && PB.encode(e, 3, x.before)
    x.replace != false && PB.encode(e, 4, x.replace)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OperationInstanceNoise)
    encoded_size = 0
    !isnothing(x.operation) && (encoded_size += PB._encoded_size(x.operation, 1))
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 2))
    x.before != false && (encoded_size += PB._encoded_size(x.before, 3))
    x.replace != false && (encoded_size += PB._encoded_size(x.replace, 4))
    return encoded_size
end

struct SetQubitReadoutNoise
    qubits::Vector{UInt32}
    noise::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{SetQubitReadoutNoise}) = (;qubits = Vector{UInt32}(), noise = nothing)
PB.field_numbers(::Type{SetQubitReadoutNoise}) = (;qubits = 1, noise = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetQubitReadoutNoise})
    qubits = PB.BufferedVector{UInt32}()
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, qubits)
        elseif field_number == 2
            PB.decode!(d, noise)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetQubitReadoutNoise(qubits[], noise[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetQubitReadoutNoise)
    initpos = position(e.io)
    !isempty(x.qubits) && PB.encode(e, 1, x.qubits)
    !isnothing(x.noise) && PB.encode(e, 2, x.noise)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetQubitReadoutNoise)
    encoded_size = 0
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 1))
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 2))
    return encoded_size
end

struct GlobalReadoutNoise
    noise::Union{Nothing,circuit_pb.Operation}
end
PB.default_values(::Type{GlobalReadoutNoise}) = (;noise = nothing)
PB.field_numbers(::Type{GlobalReadoutNoise}) = (;noise = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GlobalReadoutNoise})
    noise = Ref{Union{Nothing,circuit_pb.Operation}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, noise)
        else
            Base.skip(d, wire_type)
        end
    end
    return GlobalReadoutNoise(noise[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GlobalReadoutNoise)
    initpos = position(e.io)
    !isnothing(x.noise) && PB.encode(e, 1, x.noise)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GlobalReadoutNoise)
    encoded_size = 0
    !isnothing(x.noise) && (encoded_size += PB._encoded_size(x.noise, 1))
    return encoded_size
end

struct IdleNoise
    relation::Union{Nothing,SymbolicPattern}
end
PB.default_values(::Type{IdleNoise}) = (;relation = nothing)
PB.field_numbers(::Type{IdleNoise}) = (;relation = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IdleNoise})
    relation = Ref{Union{Nothing,SymbolicPattern}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, relation)
        else
            Base.skip(d, wire_type)
        end
    end
    return IdleNoise(relation[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IdleNoise)
    initpos = position(e.io)
    !isnothing(x.relation) && PB.encode(e, 1, x.relation)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IdleNoise)
    encoded_size = 0
    !isnothing(x.relation) && (encoded_size += PB._encoded_size(x.relation, 1))
    return encoded_size
end

struct SetIdleQubitNoise
    relation::Union{Nothing,SymbolicPattern}
    qubits::Vector{UInt32}
end
PB.default_values(::Type{SetIdleQubitNoise}) = (;relation = nothing, qubits = Vector{UInt32}())
PB.field_numbers(::Type{SetIdleQubitNoise}) = (;relation = 1, qubits = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetIdleQubitNoise})
    relation = Ref{Union{Nothing,SymbolicPattern}}(nothing)
    qubits = PB.BufferedVector{UInt32}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, relation)
        elseif field_number == 2
            PB.decode!(d, wire_type, qubits)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetIdleQubitNoise(relation[], qubits[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetIdleQubitNoise)
    initpos = position(e.io)
    !isnothing(x.relation) && PB.encode(e, 1, x.relation)
    !isempty(x.qubits) && PB.encode(e, 2, x.qubits)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetIdleQubitNoise)
    encoded_size = 0
    !isnothing(x.relation) && (encoded_size += PB._encoded_size(x.relation, 1))
    !isempty(x.qubits) && (encoded_size += PB._encoded_size(x.qubits, 2))
    return encoded_size
end

struct NoiseRule
    kind::Union{Nothing,OneOf{<:Union{GlobalReadoutNoise,ExactQubitReadoutNoise,SetQubitReadoutNoise,OperationInstanceNoise,ExactOperationInstanceQubitNoise,SetOperationInstanceQubitNoise,IdleNoise,CustomNoiseRule,SetIdleQubitNoise}}}
end
PB.oneof_field_types(::Type{NoiseRule}) = (;
    kind = (;global_readout=GlobalReadoutNoise, exact_qubit_readout=ExactQubitReadoutNoise, set_qubit_readout=SetQubitReadoutNoise, operation_instance_noise=OperationInstanceNoise, exact_operation_instance_noise=ExactOperationInstanceQubitNoise, set_operation_instance_noise=SetOperationInstanceQubitNoise, idle_noise=IdleNoise, custom_noise=CustomNoiseRule, set_idle_noise=SetIdleQubitNoise),
)
PB.default_values(::Type{NoiseRule}) = (;global_readout = nothing, exact_qubit_readout = nothing, set_qubit_readout = nothing, operation_instance_noise = nothing, exact_operation_instance_noise = nothing, set_operation_instance_noise = nothing, idle_noise = nothing, custom_noise = nothing, set_idle_noise = nothing)
PB.field_numbers(::Type{NoiseRule}) = (;global_readout = 1, exact_qubit_readout = 2, set_qubit_readout = 3, operation_instance_noise = 4, exact_operation_instance_noise = 5, set_operation_instance_noise = 6, idle_noise = 7, custom_noise = 8, set_idle_noise = 9)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:NoiseRule})
    kind = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            kind = OneOf(:global_readout, PB.decode(d, Ref{GlobalReadoutNoise}))
        elseif field_number == 2
            kind = OneOf(:exact_qubit_readout, PB.decode(d, Ref{ExactQubitReadoutNoise}))
        elseif field_number == 3
            kind = OneOf(:set_qubit_readout, PB.decode(d, Ref{SetQubitReadoutNoise}))
        elseif field_number == 4
            kind = OneOf(:operation_instance_noise, PB.decode(d, Ref{OperationInstanceNoise}))
        elseif field_number == 5
            kind = OneOf(:exact_operation_instance_noise, PB.decode(d, Ref{ExactOperationInstanceQubitNoise}))
        elseif field_number == 6
            kind = OneOf(:set_operation_instance_noise, PB.decode(d, Ref{SetOperationInstanceQubitNoise}))
        elseif field_number == 7
            kind = OneOf(:idle_noise, PB.decode(d, Ref{IdleNoise}))
        elseif field_number == 8
            kind = OneOf(:custom_noise, PB.decode(d, Ref{CustomNoiseRule}))
        elseif field_number == 9
            kind = OneOf(:set_idle_noise, PB.decode(d, Ref{SetIdleQubitNoise}))
        else
            Base.skip(d, wire_type)
        end
    end
    return NoiseRule(kind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::NoiseRule)
    initpos = position(e.io)
    if isnothing(x.kind);
    elseif x.kind.name === :global_readout
        PB.encode(e, 1, x.kind[]::GlobalReadoutNoise)
    elseif x.kind.name === :exact_qubit_readout
        PB.encode(e, 2, x.kind[]::ExactQubitReadoutNoise)
    elseif x.kind.name === :set_qubit_readout
        PB.encode(e, 3, x.kind[]::SetQubitReadoutNoise)
    elseif x.kind.name === :operation_instance_noise
        PB.encode(e, 4, x.kind[]::OperationInstanceNoise)
    elseif x.kind.name === :exact_operation_instance_noise
        PB.encode(e, 5, x.kind[]::ExactOperationInstanceQubitNoise)
    elseif x.kind.name === :set_operation_instance_noise
        PB.encode(e, 6, x.kind[]::SetOperationInstanceQubitNoise)
    elseif x.kind.name === :idle_noise
        PB.encode(e, 7, x.kind[]::IdleNoise)
    elseif x.kind.name === :custom_noise
        PB.encode(e, 8, x.kind[]::CustomNoiseRule)
    elseif x.kind.name === :set_idle_noise
        PB.encode(e, 9, x.kind[]::SetIdleQubitNoise)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::NoiseRule)
    encoded_size = 0
    if isnothing(x.kind);
    elseif x.kind.name === :global_readout
        encoded_size += PB._encoded_size(x.kind[]::GlobalReadoutNoise, 1)
    elseif x.kind.name === :exact_qubit_readout
        encoded_size += PB._encoded_size(x.kind[]::ExactQubitReadoutNoise, 2)
    elseif x.kind.name === :set_qubit_readout
        encoded_size += PB._encoded_size(x.kind[]::SetQubitReadoutNoise, 3)
    elseif x.kind.name === :operation_instance_noise
        encoded_size += PB._encoded_size(x.kind[]::OperationInstanceNoise, 4)
    elseif x.kind.name === :exact_operation_instance_noise
        encoded_size += PB._encoded_size(x.kind[]::ExactOperationInstanceQubitNoise, 5)
    elseif x.kind.name === :set_operation_instance_noise
        encoded_size += PB._encoded_size(x.kind[]::SetOperationInstanceQubitNoise, 6)
    elseif x.kind.name === :idle_noise
        encoded_size += PB._encoded_size(x.kind[]::IdleNoise, 7)
    elseif x.kind.name === :custom_noise
        encoded_size += PB._encoded_size(x.kind[]::CustomNoiseRule, 8)
    elseif x.kind.name === :set_idle_noise
        encoded_size += PB._encoded_size(x.kind[]::SetIdleQubitNoise, 9)
    end
    return encoded_size
end

struct NoiseModel
    name::String
    rules::Vector{NoiseRule}
end
PB.default_values(::Type{NoiseModel}) = (;name = "", rules = Vector{NoiseRule}())
PB.field_numbers(::Type{NoiseModel}) = (;name = 1, rules = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:NoiseModel})
    name = ""
    rules = PB.BufferedVector{NoiseRule}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, rules)
        else
            Base.skip(d, wire_type)
        end
    end
    return NoiseModel(name, rules[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::NoiseModel)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.rules) && PB.encode(e, 2, x.rules)
    return position(e.io) - initpos
end
function PB._encoded_size(x::NoiseModel)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.rules) && (encoded_size += PB._encoded_size(x.rules, 2))
    return encoded_size
end
end # module