# Autogenerated using ProtoBuf.jl v1.2.3


module optim_pb


import ..circuit_pb

import ..qcsresults_pb

import ..hamiltonian_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ParametersDictItem, OptimizationExperiment, OptimizationRun, OptimizationResults


struct ParametersDictItem
    key::Union{Nothing,circuit_pb.Symbol}
    value::Float64
end
PB.default_values(::Type{ParametersDictItem}) = (;key = nothing, value = zero(Float64))
PB.field_numbers(::Type{ParametersDictItem}) = (;key = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ParametersDictItem})
    key = Ref{Union{Nothing,circuit_pb.Symbol}}(nothing)
    value = zero(Float64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, key)
        elseif field_number == 2
            value = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return ParametersDictItem(key[], value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ParametersDictItem)
    initpos = position(e.io)
    !isnothing(x.key) && PB.encode(e, 1, x.key)
    x.value !== zero(Float64) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ParametersDictItem)
    encoded_size = 0
    !isnothing(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    x.value !== zero(Float64) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct OptimizationExperiment
    circuit::Union{Nothing,circuit_pb.Circuit}
    optimizer::String
    initparams::Vector{ParametersDictItem}
    maxiters::UInt64
    zregister::UInt64
    label::String
end
PB.default_values(::Type{OptimizationExperiment}) = (;circuit = nothing, optimizer = "", initparams = Vector{ParametersDictItem}(), maxiters = zero(UInt64), zregister = zero(UInt64), label = "")
PB.field_numbers(::Type{OptimizationExperiment}) = (;circuit = 1, optimizer = 2, initparams = 3, maxiters = 4, zregister = 5, label = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OptimizationExperiment})
    circuit = Ref{Union{Nothing,circuit_pb.Circuit}}(nothing)
    optimizer = ""
    initparams = PB.BufferedVector{ParametersDictItem}()
    maxiters = zero(UInt64)
    zregister = zero(UInt64)
    label = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, circuit)
        elseif field_number == 2
            optimizer = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, initparams)
        elseif field_number == 4
            maxiters = PB.decode(d, UInt64)
        elseif field_number == 5
            zregister = PB.decode(d, UInt64)
        elseif field_number == 6
            label = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return OptimizationExperiment(circuit[], optimizer, initparams[], maxiters, zregister, label)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OptimizationExperiment)
    initpos = position(e.io)
    !isnothing(x.circuit) && PB.encode(e, 1, x.circuit)
    !isempty(x.optimizer) && PB.encode(e, 2, x.optimizer)
    !isempty(x.initparams) && PB.encode(e, 3, x.initparams)
    x.maxiters != zero(UInt64) && PB.encode(e, 4, x.maxiters)
    x.zregister != zero(UInt64) && PB.encode(e, 5, x.zregister)
    !isempty(x.label) && PB.encode(e, 6, x.label)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OptimizationExperiment)
    encoded_size = 0
    !isnothing(x.circuit) && (encoded_size += PB._encoded_size(x.circuit, 1))
    !isempty(x.optimizer) && (encoded_size += PB._encoded_size(x.optimizer, 2))
    !isempty(x.initparams) && (encoded_size += PB._encoded_size(x.initparams, 3))
    x.maxiters != zero(UInt64) && (encoded_size += PB._encoded_size(x.maxiters, 4))
    x.zregister != zero(UInt64) && (encoded_size += PB._encoded_size(x.zregister, 5))
    !isempty(x.label) && (encoded_size += PB._encoded_size(x.label, 6))
    return encoded_size
end

struct OptimizationRun
    cost::Float64
    parameters::Vector{ParametersDictItem}
    results::Union{Nothing,qcsresults_pb.QCSResults}
end
PB.default_values(::Type{OptimizationRun}) = (;cost = zero(Float64), parameters = Vector{ParametersDictItem}(), results = nothing)
PB.field_numbers(::Type{OptimizationRun}) = (;cost = 1, parameters = 2, results = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OptimizationRun})
    cost = zero(Float64)
    parameters = PB.BufferedVector{ParametersDictItem}()
    results = Ref{Union{Nothing,qcsresults_pb.QCSResults}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            cost = PB.decode(d, Float64)
        elseif field_number == 2
            PB.decode!(d, parameters)
        elseif field_number == 3
            PB.decode!(d, results)
        else
            Base.skip(d, wire_type)
        end
    end
    return OptimizationRun(cost, parameters[], results[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OptimizationRun)
    initpos = position(e.io)
    x.cost !== zero(Float64) && PB.encode(e, 1, x.cost)
    !isempty(x.parameters) && PB.encode(e, 2, x.parameters)
    !isnothing(x.results) && PB.encode(e, 3, x.results)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OptimizationRun)
    encoded_size = 0
    x.cost !== zero(Float64) && (encoded_size += PB._encoded_size(x.cost, 1))
    !isempty(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    !isnothing(x.results) && (encoded_size += PB._encoded_size(x.results, 3))
    return encoded_size
end

struct OptimizationResults
    best::Union{Nothing,OptimizationRun}
    history::Vector{OptimizationRun}
end
PB.default_values(::Type{OptimizationResults}) = (;best = nothing, history = Vector{OptimizationRun}())
PB.field_numbers(::Type{OptimizationResults}) = (;best = 1, history = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OptimizationResults})
    best = Ref{Union{Nothing,OptimizationRun}}(nothing)
    history = PB.BufferedVector{OptimizationRun}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, best)
        elseif field_number == 2
            PB.decode!(d, history)
        else
            Base.skip(d, wire_type)
        end
    end
    return OptimizationResults(best[], history[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OptimizationResults)
    initpos = position(e.io)
    !isnothing(x.best) && PB.encode(e, 1, x.best)
    !isempty(x.history) && PB.encode(e, 2, x.history)
    return position(e.io) - initpos
end
function PB._encoded_size(x::OptimizationResults)
    encoded_size = 0
    !isnothing(x.best) && (encoded_size += PB._encoded_size(x.best, 1))
    !isempty(x.history) && (encoded_size += PB._encoded_size(x.history, 2))
    return encoded_size
end
end # module