# Autogenerated using ProtoBuf.jl v1.2.3


module pauli_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export PauliString


struct PauliString
    numqubits::Int64
    pauli::String
end
PB.default_values(::Type{PauliString}) = (;numqubits = zero(Int64), pauli = "")
PB.field_numbers(::Type{PauliString}) = (;numqubits = 1, pauli = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:PauliString})
    numqubits = zero(Int64)
    pauli = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            numqubits = PB.decode(d, Int64)
        elseif field_number == 2
            pauli = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return PauliString(numqubits, pauli)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::PauliString)
    initpos = position(e.io)
    x.numqubits != zero(Int64) && PB.encode(e, 1, x.numqubits)
    !isempty(x.pauli) && PB.encode(e, 2, x.pauli)
    return position(e.io) - initpos
end
function PB._encoded_size(x::PauliString)
    encoded_size = 0
    x.numqubits != zero(Int64) && (encoded_size += PB._encoded_size(x.numqubits, 1))
    !isempty(x.pauli) && (encoded_size += PB._encoded_size(x.pauli, 2))
    return encoded_size
end
end # module