#
# Copyright © 2022-2024 University of Strasbourg. All Rights Reserved.
# Copyright © 2023-2025 QPerfect. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ==================================================== #
# Core decoration functions with matcher and generator #
# ==================================================== #

"""
    decorate_on_match_single!(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)

Modifies a circuit in-place by adding instructions generated by a `generator` function 
next to each instruction identified by a `matcher` function.

For each instruction that satisfies the `matcher`, a corresponding instruction is
generated using the `generator` function and inserted either before or after the 
matched instruction.

# Arguments
- `circuit`: The circuit to modify
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add the generated instruction before the matched one (default: `false`)

# Returns
The modified circuit

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1);

julia> push!(c, GateX(), 2);

julia> push!(c, GateH(), 3);

julia> matcher(inst) = getoperation(inst) isa GateH;

julia> generator(inst) = Instruction(GateZ(), getqubits(inst)...);

julia> decorate_on_match_single!(c, matcher, generator)
3-qubit circuit with 5 instructions:
├── H @ q[1]
├── Z @ q[1]
├── X @ q[2]
├── H @ q[3]
└── Z @ q[3]
```
"""
function decorate_on_match_single!(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)
    rel_pos = before ? 0 : 1

    i = 1
    while i <= length(circuit)
        inst = circuit[i]

        if matcher(inst)
            generated = generator(inst)
            insert!(circuit, i + rel_pos, generated)
            i += 2  # Skip both original and newly added instruction
        else
            i += 1
        end
    end

    return circuit
end

"""
    decorate_on_match_single(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)

Creates a new circuit by adding instructions generated by a `generator` function 
next to each instruction identified by a `matcher` function.

Non-mutating version of [`decorate_on_match_single!`](@ref).

# Arguments
- `circuit`: The original circuit (not modified)
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add the generated instruction before the matched one (default: `false`)

# Returns
A new circuit with decorations added

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1);

julia> push!(c, GateX(), 2);

julia> matcher(inst) = getoperation(inst) isa GateH;

julia> generator(inst) = Instruction(GateT(), getqubits(inst)...);

julia> c2 = decorate_on_match_single(c, matcher, generator; before=true)
2-qubit circuit with 3 instructions:
├── T @ q[1]
├── H @ q[1]
└── X @ q[2]

```
"""
function decorate_on_match_single(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)
    newcircuit = Circuit()

    for inst in circuit
        if matcher(inst)
            generated = generator(inst)

            if before
                push!(newcircuit, generated)
                push!(newcircuit, inst)
            else
                push!(newcircuit, inst)
                push!(newcircuit, generated)
            end
        else
            push!(newcircuit, inst)
        end
    end

    return newcircuit
end

# Internal helper to find a transversal block
function _find_transversal_block(circuit::Circuit, i::Int, matcher::Function, generator::Function)
    inst = circuit[i]
    original_block = [inst]
    generated = generator(inst)
    generated_block = [generated]

    # Track all resources used
    qubits_in_block = Set(getqubits(inst))
    bits_in_block = Set(getbits(inst))
    vars_in_block = Set(getztargets(inst))

    qubits_in_generated = Set(getqubits(generated))
    bits_in_generated = Set(getbits(generated))
    vars_in_generated = Set(getztargets(generated))

    # Greedily search for more instructions to add to the block
    j = i + 1
    while j <= length(circuit)
        nextinst = circuit[j]
        nextqubits = getqubits(nextinst)
        nextbits = getbits(nextinst)
        nextvars = getztargets(nextinst)

        # Check if we can extend the block
        if matcher(nextinst) &&
           isdisjoint(qubits_in_block, nextqubits) && isdisjoint(qubits_in_generated, nextqubits) &&
           isdisjoint(bits_in_block, nextbits) && isdisjoint(bits_in_generated, nextbits) &&
           isdisjoint(vars_in_block, nextvars) && isdisjoint(vars_in_generated, nextvars)

            generated = generator(nextinst)

            push!(original_block, nextinst)
            push!(generated_block, generated)

            union!(qubits_in_block, nextqubits)
            union!(bits_in_block, nextbits)
            union!(vars_in_block, nextvars)

            union!(qubits_in_generated, getqubits(generated))
            union!(bits_in_generated, getbits(generated))
            union!(vars_in_generated, getztargets(generated))

            j += 1
        else
            break
        end
    end

    return (original_block=original_block, generated_block=generated_block)
end

"""
    decorate_on_match_parallel!(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)

Modifies a circuit in-place by adding blocks of instructions next to transversal blocks 
of instructions identified by a `matcher` function.

This function identifies consecutive instructions that satisfy the matcher and act on 
disjoint resources (qubits, classical bits, variables), treating them as a transversal block.
It then generates a corresponding block of decorations and inserts it before or after
the entire original block.

# Arguments
- `circuit`: The circuit to modify
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add the generated block before the matched block (default: `false`)

# Returns
The modified circuit

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1:3);  # Transversal H gates

julia> push!(c, GateX(), 1);

julia> matcher(inst) = getoperation(inst) isa GateH;

julia> generator(inst) = Instruction(GateS(), getqubits(inst)...);

julia> decorate_on_match_parallel!(c, matcher, generator)
3-qubit circuit with 7 instructions:
├── H @ q[1]
├── H @ q[2]
├── H @ q[3]
├── S @ q[1]
├── S @ q[2]
├── S @ q[3]
└── X @ q[1]

```
"""
function decorate_on_match_parallel!(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)
    i = 1
    while i <= length(circuit)
        inst = circuit[i]

        if matcher(inst)
            blocks = _find_transversal_block(circuit, i, matcher, generator)
            original_block = blocks.original_block
            generated_block = blocks.generated_block
            block_size = length(original_block)

            if before
                for k in 1:block_size
                    insert!(circuit, i + (k - 1), generated_block[k])
                end
            else
                insert_pos = (i + block_size - 1) + 1
                for k in 1:block_size
                    insert!(circuit, insert_pos + (k - 1), generated_block[k])
                end
            end

            i += 2 * block_size
        else
            i += 1
        end
    end

    return circuit
end

"""
    decorate_on_match_parallel(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)

Creates a new circuit by adding blocks of instructions next to transversal blocks 
of instructions identified by a `matcher` function.

Non-mutating version of [`decorate_on_match_parallel!`](@ref).

# Arguments
- `circuit`: The original circuit (not modified)
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add the generated block before the matched block (default: `false`)

# Returns
A new circuit with decorations added

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1:3);  # Transversal H gates

julia> matcher(inst) = getoperation(inst) isa GateH;

julia> generator(inst) = Instruction(GateT(), getqubits(inst)...);

julia> c2 = decorate_on_match_parallel(c, matcher, generator; before=true)
3-qubit circuit with 6 instructions:
├── T @ q[1]
├── T @ q[2]
├── T @ q[3]
├── H @ q[1]
├── H @ q[2]
└── H @ q[3]

```
"""
function decorate_on_match_parallel(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false)
    newcircuit = Circuit()
    i = 1
    while i <= length(circuit)
        inst = circuit[i]
        if matcher(inst)
            blocks = _find_transversal_block(circuit, i, matcher, generator)
            original_block = blocks.original_block
            generated_block = blocks.generated_block

            if before
                append!(newcircuit, generated_block)
                append!(newcircuit, original_block)
            else
                append!(newcircuit, original_block)
                append!(newcircuit, generated_block)
            end

            i += length(original_block)
        else
            push!(newcircuit, inst)
            i += 1
        end
    end
    return newcircuit
end

# ================================#
# High-level decoration functions #
# =============================== #

"""
    decorate(circuit::Circuit, matcher::Function, generator::Function; before=false, parallel=false)

Creates a new decorated circuit by adding generated instructions next to matched instructions.

This is the main non-mutating interface for circuit decoration. It combines the functionality
of single and parallel decoration based on the `parallel` parameter.

# Arguments
- `circuit`: The original circuit (not modified)
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add decorations before matched instructions (default: `false`)
- `parallel`: If `true`, group transversal operations into blocks (default: `false`)

# Returns
A new circuit with decorations added

# Examples

## Basic decoration with custom matcher and generator
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1);

julia> push!(c, GateX(), 2);

julia> push!(c, GateH(), 3);

julia> is_hadamard(inst) = getoperation(inst) isa GateH;

julia> add_phase(inst) = Instruction(GateS(), getqubits(inst)...);

julia> c2 = decorate(c, is_hadamard, add_phase)
3-qubit circuit with 5 instructions:
├── H @ q[1]
├── S @ q[1]
├── X @ q[2]
├── H @ q[3]
└── S @ q[3]

```

## Parallel decoration for transversal operations
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1:4);

julia> c2 = decorate(c, 
           inst -> getoperation(inst) isa GateH,
           inst -> Instruction(GateT(), getqubits(inst)...);
           parallel=true)
4-qubit circuit with 8 instructions:
├── H @ q[1]
├── H @ q[2]
├── H @ q[3]
├── H @ q[4]
├── T @ q[1]
├── T @ q[2]
├── T @ q[3]
└── T @ q[4]
```
"""
function decorate(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false, parallel::Bool=false)
    if !parallel
        return decorate_on_match_single(circuit, matcher, generator; before=before)
    else
        return decorate_on_match_parallel(circuit, matcher, generator; before=before)
    end
end

"""
    decorate!(circuit::Circuit, matcher::Function, generator::Function; before=false, parallel=false)

Modifies a circuit in-place by adding generated instructions next to matched instructions.

This is the main mutating interface for circuit decoration. It combines the functionality
of single and parallel decoration based on the `parallel` parameter.

# Arguments
- `circuit`: The circuit to modify
- `matcher`: A function that takes an instruction and returns `true` if it should be decorated
- `generator`: A function that takes a matched instruction and returns a new instruction to add
- `before`: If `true`, add decorations before matched instructions (default: `false`)
- `parallel`: If `true`, group transversal operations into blocks (default: `false`)

# Returns
The modified circuit

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateX(), 1);

julia> push!(c, GateY(), 2);

julia> decorate!(c,
           inst -> getoperation(inst) isa GateX,
           inst -> Instruction(GateH(), getqubits(inst)...);
           before=true)
2-qubit circuit with 3 instructions:
├── H @ q[1]
├── X @ q[1]
└── Y @ q[2]

```
"""
function decorate!(circuit::Circuit, matcher::Function, generator::Function; before::Bool=false, parallel::Bool=false)
    if !parallel
        return decorate_on_match_single!(circuit, matcher, generator; before=before)
    else
        return decorate_on_match_parallel!(circuit, matcher, generator; before=before)
    end
end

"""
    decorate(circuit::Circuit, target::Operation, decoration::Operation; before=false, parallel=false)

Creates a new circuit by adding `decoration` operations next to all instances of `target` operation.

# Arguments
- `circuit`: The original circuit (not modified)
- `target`: The specific operation to decorate
- `decoration`: The operation to add as decoration
- `before`: If `true`, add decorations before target operations (default: `false`)
- `parallel`: If `true`, group transversal operations into blocks (default: `false`)

# Returns
A new circuit with decorations added

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1:2);

julia> push!(c, GateX(), 1);

julia> c2 = decorate(c, GateH(), GateS())
2-qubit circuit with 5 instructions:
├── H @ q[1]
├── S @ q[1]
├── H @ q[2]
├── S @ q[2]
└── X @ q[1]

```
"""
function decorate(circuit::Circuit, target::Operation{N,L,M}, decoration::Operation{N,L,M}; before::Bool=false, parallel::Bool=false) where {N,L,M}
    matcher(inst) = getoperation(inst) == target
    generator(inst) = Instruction(decoration, getqubits(inst)..., getbits(inst)..., getztargets(inst)...)
    return decorate(circuit, matcher, generator; before=before, parallel=parallel)
end

"""
    decorate!(circuit::Circuit, target::Operation, decoration::Operation; before=false, parallel=false)

Modifies a circuit in-place by adding `decoration` operations next to all instances of `target` operation.

Mutating version of [`decorate`](@ref).
"""
function decorate!(circuit::Circuit, target::Operation{N,L,M}, decoration::Operation{N,L,M}; before::Bool=false, parallel::Bool=false) where {N,L,M}
    matcher(inst) = getoperation(inst) == target
    generator(inst) = Instruction(decoration, getqubits(inst)..., getbits(inst)..., getztargets(inst)...)
    return decorate!(circuit, matcher, generator; before=before, parallel=parallel)
end

"""
    decorate(circuit::Circuit, target::Type{<:Operation}, decoration::Operation; before=false, parallel=false)

Creates a new circuit by adding `decoration` operations next to all operations of type `target`.

# Arguments
- `circuit`: The original circuit (not modified)
- `target`: The type of operations to decorate
- `decoration`: The operation to add as decoration
- `before`: If `true`, add decorations before target operations (default: `false`)
- `parallel`: If `true`, group transversal operations into blocks (default: `false`)

# Returns
A new circuit with decorations added

# Examples
```jldoctest
julia> c = Circuit();

julia> push!(c, GateH(), 1);

julia> push!(c, GateX(), 3);

julia> c2 = decorate(c, GateH, GateT(); before=true)
3-qubit circuit with 3 instructions:
├── T @ q[1]
├── H @ q[1]
└── X @ q[3]

```
"""
function decorate(circuit::Circuit, target::Type{<:Operation{N,L,M}}, decoration::Operation{N,L,M}; before::Bool=false, parallel::Bool=false) where {N,L,M}
    matcher(inst) = getoperation(inst) isa target
    generator(inst) = Instruction(decoration, getqubits(inst)..., getbits(inst)..., getztargets(inst)...)
    return decorate(circuit, matcher, generator; before=before, parallel=parallel)
end

"""
    decorate!(circuit::Circuit, target::Type{<:Operation}, decoration::Operation; before=false, parallel=false)

Modifies a circuit in-place by adding `decoration` operations next to all operations of type `target`.

Mutating version of [`decorate`](@ref).
"""
function decorate!(circuit::Circuit, target::Type{<:Operation{N,L,M}}, decoration::Operation{N,L,M}; before::Bool=false, parallel::Bool=false) where {N,L,M}
    matcher(inst) = getoperation(inst) isa target
    generator(inst) = Instruction(decoration, getqubits(inst)..., getbits(inst)..., getztargets(inst)...)
    return decorate!(circuit, matcher, generator; before=before, parallel=parallel)
end

function decorate(circuit::Circuit, target::AbstractMeasurement{N}, decoration::Operation{N,0,0}; before::Bool=false, parallel::Bool=false) where {N}
    matcher(inst) = getoperation(inst) == target
    generator(inst) = Instruction(decoration, getqubits(inst)...)
    return decorate(circuit, matcher, generator; before=before, parallel=parallel)
end

function decorate!(circuit::Circuit, target::AbstractMeasurement{N}, decoration::Operation{N,0,0}; before::Bool=false, parallel::Bool=false) where {N}
    matcher(inst) = getoperation(inst) == target
    generator(inst) = Instruction(decoration, getqubits(inst)...)
    return decorate!(circuit, matcher, generator; before=before, parallel=parallel)
end

function decorate(circuit::Circuit, target::Type{<:AbstractMeasurement{N}}, decoration::Operation{N,0,0}; before::Bool=false, parallel::Bool=false) where {N}
    matcher(inst) = getoperation(inst) isa target
    generator(inst) = Instruction(decoration, getqubits(inst)...)
    return decorate(circuit, matcher, generator; before=before, parallel=parallel)
end

function decorate!(circuit::Circuit, target::Type{<:AbstractMeasurement{N}}, decoration::Operation{N,0,0}; before::Bool=false, parallel::Bool=false) where {N}
    matcher(inst) = getoperation(inst) isa target
    generator(inst) = Instruction(decoration, getqubits(inst)...)
    return decorate!(circuit, matcher, generator; before=before, parallel=parallel)
end

# =========================================== #
# Backward compatibility: add_noise functions #
# =========================================== #

"""
    add_noise!(c, g, noise; before=false, parallel=false)

Add a noise operation `noise` to every operation `g` in the circuit `c`.

The noise operation `noise` can be a Kraus channel or a gate and will act on the same qubits
as the operation `g` it is being added to. The operations `g` and `noise` must act on the 
same number of qubits.

!!! warn
    This function is maintained for backward compatibility. Consider using
    [`decorate!`](@ref) for more general decoration needs.

# Arguments
- `c`: Circuit to modify
- `g`: Operation to which noise will be added
- `noise`: Kraus channel or gate that will be added to each operation `g`
- `before`: If `true`, add noise before the operation (default: `false`)
- `parallel`: If `true`, group transversal operations into blocks (default: `false`)

# Returns
The circuit `c` with the noise added in place

# Examples

## Parallel vs not parallel
```jldoctest
julia> c = push!(Circuit(), GateH(), 1:3);

julia> add_noise!(c, GateH(), AmplitudeDamping(0.2))
3-qubit circuit with 6 instructions:
├── H @ q[1]
├── AmplitudeDamping(0.2) @ q[1]
├── H @ q[2]
├── AmplitudeDamping(0.2) @ q[2]
├── H @ q[3]
└── AmplitudeDamping(0.2) @ q[3]

julia> c = push!(Circuit(), GateH(), 1:3);

julia> add_noise!(c, GateH(), AmplitudeDamping(0.2); parallel=true)
3-qubit circuit with 6 instructions:
├── H @ q[1]
├── H @ q[2]
├── H @ q[3]
├── AmplitudeDamping(0.2) @ q[1]
├── AmplitudeDamping(0.2) @ q[2]
└── AmplitudeDamping(0.2) @ q[3]
```

## Noise before measurements
```jldoctest
julia> c = push!(Circuit(), Measure(), 1:3, 1:3);

julia> add_noise!(c, Measure(), PauliX(0.1); before=true)
3-qubit, 3-bit circuit with 6 instructions:
├── PauliX(0.1) @ q[1]
├── M @ q[1], c[1]
├── PauliX(0.1) @ q[2]
├── M @ q[2], c[2]
├── PauliX(0.1) @ q[3]
└── M @ q[3], c[3]

```
"""
function add_noise!(c::Circuit, g::Union{Operation,Type{<:Operation}}, noise::Union{AbstractKrausChannel,AbstractGate};
    before::Bool=false, parallel::Bool=false)

    if numqubits(g) != numqubits(noise)
        error("Noise channel and operation must have the same number of target qubits")
    end

    return decorate!(c, g, noise; before=before, parallel=parallel)
end

"""
    add_noise(c, g, noise; before=false, parallel=false)

Add noise operation `noise` to every operation `g` in circuit `c`.

A copy of `c` is created and then noise is added to the copy.

!!! warn
    This function is maintained for backward compatibility. Consider using
    [`decorate`](@ref) for more general decoration needs.

See [`add_noise!`](@ref) for more information.
"""
function add_noise(c::Circuit, g::Union{Operation,Type{<:Operation}}, noise::Union{AbstractKrausChannel,AbstractGate};
    before::Bool=false, parallel::Bool=false)

    if numqubits(g) != numqubits(noise)
        error("Noise channel and operation must have the same number of target qubits")
    end

    circ = Circuit()
    for inst in c
        push!(circ, inst)
    end

    return decorate!(circ, g, noise; before=before, parallel=parallel)
end
